Add Salla / ecommerce
wappalyzer/wappalyzer pull request #5990
Opened 2022-04-01 14:38 UTC by ahmedelq

## Website:

https://salla.sa/

## Examples:
https://www.soollz.com/

2022-04-01 15:00 UTC, nurbek91 approved these changes
Hey mate, thanks for PR!!!
Need minor updates to make it perfect

2022-04-01 15:00 UTC, nurbek91 commented on src/technologies/s.json
> +	  "x-powered-by": "Salla"
Let's change the regex to avoid false positives
` "x-powered-by": "^Salla$"`

2022-04-01 15:00 UTC, nurbek91 commented on src/technologies/s.json
> +    "dom": "img[src*='cdn.salla.sa']",
Is this identifier necessary?
We need an example of sites where the header attribute and the scriptSrc are missing. Are there such cases?

2022-04-01 16:27 UTC, ahmedelq commented on src/technologies/s.json
> +  "Salla": {
Yes this icon is correct.

2022-04-01 16:33 UTC, ahmedelq commented on src/technologies/s.json
> +    "dom": "img[src*='cdn.salla.sa']",
Not aware about such cases. 
The `x-powered-by` is enough I guess.

2022-04-01 17:56 UTC, nurbek91 requested changes
Okay, thanks for the detailed answers, waiting for updates from you.

2022-04-06 20:27 UTC, ahmedelq commented
is there anything else you want me to add/remove?

2022-04-06 22:39 UTC, merged

2022-04-06 22:39 UTC, AliasIO commented
All good, thanks!