added utterances
wappalyzer/wappalyzer pull request #6210
Opened 2022-04-27 14:51 UTC by ahmedelq

## Website
https://utteranc.es/
## Examples
https://haxe.org/manual/introduction.html

2022-04-27 17:26 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!
A few tips to perfect your request

2022-04-27 17:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "dom": "iframe[src*='^(https?:\/\/)?(www\.)?utteranc\.es/client.js']",
"dom": "iframe[src*='^(https?:\/\/)?(www\.)?utteranc\.es/client.js']",

"dom": "iframe[src*='utteranc.es/client.js']",

2022-04-27 17:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "description":"A lightweight comments widget built on GitHub issues",
utterances is a lightweight comments widget built on GitHub issues.

2022-04-27 17:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "icon": "utterances.png",
icon should be 32x32
also we can add oss property

2022-04-28 07:24 UTC, ahmedelq commented on src/technologies/u.json
> +    "icon": "utterances.png",
done

2022-04-28 17:45 UTC, nurbek91 commented on src/technologies/u.json
> +    "xhr": "\.utteranc\.es",
`\\.utteranc\\.es`

2022-04-28 17:46 UTC, nurbek91 commented on src/technologies/u.json
> +    "description":"Utterances is a lightweight comments widget built on GitHub issues",
utterances is a lightweight comments widget built on GitHub issues.

2022-04-28 23:26 UTC, merged

2022-04-28 23:26 UTC, AliasIO commented
I fixed those up, thanks!