Add Helium Web FRAMEWORK
wappalyzer/wappalyzer pull request #6250
Opened 2022-05-04 21:30 UTC by Adrikikicp

2022-05-06 07:45 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
To add a technology, you need at least 3 or more examples.

2022-05-06 07:45 UTC, nurbek91 commented on src/technologies/h.json
> +    "website": "https://heliumweb.adrikikicp-development.ml"
https://github.com/Adrikikicp/heliumweb.adrikikicp-development.ml ?

2022-05-07 22:44 UTC, Adrikikicp commented on src/technologies/h.json
> +    "website": "https://heliumweb.adrikikicp-development.ml"
yes. And was created in Netlify

2022-05-07 23:08 UTC, Adrikikicp commented
Website: https://heliumweb.adrikikicp-development.ml

Examples:

http://cloud.vfhost.ml
http://trust.enriquitomcfh.ml
http://enriquitomcfh.ml

2022-05-10 07:59 UTC, merged

2022-05-10 07:59 UTC, AliasIO commented
Thanks!