Add lite-youtube-embed detection
wappalyzer/wappalyzer pull request #6252
Opened 2022-05-05 16:15 UTC by kevinfarrugia

GitHub page: https://github.com/paulirish/lite-youtube-embed (4.2k stars)
Demo: https://paulirish.github.io/lite-youtube-embed/

**node src/drivers/npm/cli.js https://paulirish.github.io/lite-youtube-embed/**
```
{
  "urls": {
    "https://paulirish.github.io/lite-youtube-embed/": { "status": 200 }
  },
  "technologies": [
    // ...
    {
      "slug": "lite-youtube-embed",
      "name": "lite-youtube-embed",
      "confidence": 100,
      "version": null,
      "icon": "YouTube.png",
      "website": "https://github.com/paulirish/lite-youtube-embed",
      "cpe": null,
      "categories": [
        {
          "id": 59,
          "slug": "javascript-libraries",
          "name": "JavaScript libraries"
        }
      ]
    }
    // ...
  ]
}

```

Sample pages (selected at random): 
- https://www.techbang.com/
- https://www.musicnotes.com/
- https://www.cgtrader.com/
- https://connectify.me/
- https://www.driversupport.com/
- https://www.canalturf.com/
- https://saucelabs.com/

Note: The technology does not have its own icon so I reused the YouTube icon.

2022-05-05 19:39 UTC, radum commented on src/technologies/l.json
> +  "lite-youtube-embed": {
@slightlyoff made a lite vimeo also. Might be good to add it here also.

https://github.com/slightlyoff/lite-vimeo

2022-05-05 20:52 UTC, kevinfarrugia commented on src/technologies/l.json
> +  "lite-youtube-embed": {
True, but I do not think it meets the requirements as per https://github.com/wappalyzer/wappalyzer/blob/master/CONTRIBUTING.md#adding-a-new-technology.

If the maintainers want to have it added, I can create a new PR.

2022-05-06 08:17 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!
Minor updates needed to perfect your request.

2022-05-06 08:17 UTC, nurbek91 commented on src/technologies/l.json
> +    "description": "A faster youtube embed.",
`"description": "The lite-youtube-embed  technique renders the YouTube video inside the IFRAME tag only when the play button in clicked thus improving the core web vitals score of your website.",`

2022-05-06 08:17 UTC, nurbek91 commented on src/technologies/l.json
> +    "html": "<(?:lite-youtube)",
The html attribute is resource intensive so should be replaced with **js** and/or **scriptSrc** where possible: 
```
"js": {
      "LiteYTEmbed": ""
    },
    "scriptSrc": "/lite-yt-embed\\.js",

```
But if you want to check for a special tag anyway `"html": "<(?:lite-youtube)"` you can rewrite it like this: 
`"dom": "lite-youtube",`
But in our case  js and scriptSrc I think will be sufficient.

2022-05-06 08:17 UTC, nurbek91 commented on src/technologies/l.json
> +    "icon": "YouTube.png",
The attribute of the icon can be removed, it's not the icon of this library.
or rewrite:  
"icon": "default.svg",

2022-05-06 08:17 UTC, nurbek91 commented on src/technologies/l.json
> +    "website": "https://github.com/paulirish/lite-youtube-embed"
We can also add two additional useful attributes:
```
"oss": true, 
"implies": "YouTube",
```

2022-05-10 07:58 UTC, merged

2022-05-10 07:58 UTC, AliasIO commented
Thanks!