Add nopStation ecommerce as technology
wappalyzer/wappalyzer pull request #6358
Opened 2022-06-08 09:37 UTC by kazirahiv

NopStation builts custom ecommerce solutions with custom integrations and custom built plugins based on tailored requirements on top of NopCommerce. Adding entry to detect sites built with nopCommerce and nopCommerce plugins

2022-06-11 11:30 UTC, nurbek91 commented
Hey mate, thanks for PR.
I'm not sure if nopStation can be added as a separate technology for ecommerce
examples:
https://nrbbazaar.com/
https://purplebybanu.com/
https://gasgasshopping.at/
https://motoshop24.ch/

On all the examples that I have tested it is either plugins or themes for nopCommerce
Probably it will be possible to add technology under category 19

2022-06-11 11:34 UTC, nurbek91 requested changes
.

2022-06-11 11:34 UTC, nurbek91 commented on src/technologies/n.json
> +      "generator": "^nopStation$"
Do you have examples of sites with this fingerprint?

2022-06-11 11:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "html": "<a[^>]+nop-station",
It is not advisable to use html now
it can be replaced with dom

2022-06-11 11:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "oss": true,
I think this field is invalid

2022-06-11 11:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "description": "One stop e-commerce solution with custom integrations and custom built plugins based on custom tailored requirements on top of NopCommerce",
nopStation is a one stop ecommerce solution with custom integrations and custom built plugins based on custom tailored requirements on top of nopCommerce.

2022-06-11 11:38 UTC, nurbek91 commented
![nopStation](https://user-images.githubusercontent.com/3456008/173186291-fa18e69c-7050-4f85-aee0-de67e7a83579.png)
32x32

2022-06-15 09:42 UTC, kazirahiv commented on src/technologies/n.json
> +      "generator": "^nopStation$"
removed the meta tag

2022-06-15 09:42 UTC, kazirahiv commented on src/technologies/n.json
> +    "html": "<a[^>]+nop-station",
Replaced with dom

2022-06-15 09:42 UTC, kazirahiv commented on src/technologies/n.json
> +    "oss": true,
Removed the oss field

2022-06-15 09:43 UTC, kazirahiv commented
@nurbek91 Hi, Made the changes, Added a new commit. Can you please check now ?

2022-06-15 09:47 UTC, kazirahiv commented
> 

There is a lot of websites that we made but most of them has our plugins/integrations etc. So I added 6, 19 both.

2022-06-15 10:54 UTC, nurbek91 commented
> > 
> 
> There is a lot of websites that we made but most of them has our plugins/integrations etc. So I added 6, 19 both.

Hi, for 6 we try to define always one technology.
So we need to add the attribute:
`"exclude": "nopCommerce"`

But I'm not sure about this.

2022-06-15 11:08 UTC, kazirahiv commented
> > > 
> > 
> > 
> > There is a lot of websites that we made but most of them has our plugins/integrations etc. So I added 6, 19 both.
> 
> Hi, for 6 we try to define always one technology. So we need to add the attribute: `"exclude": "nopCommerce"`
> 
> But I'm not sure about this.

Added the excludes property.

2022-06-15 11:28 UTC, nurbek91 commented
> > > > 
> > > 
> > > 
> > > There is a lot of websites that we made but most of them has our plugins/integrations etc. So I added 6, 19 both.
> > 
> > 
> > Hi, for 6 we try to define always one technology. So we need to add the attribute: `"exclude": "nopCommerce"`
> > But I'm not sure about this.
> 
> Added the excludes property.

But I'm not sure about this. It will probably still be correct to specify category 19 and add requires `"requires": "nopCommerce"`

2022-06-15 11:30 UTC, nurbek91 commented
Exactly how it will be right most likely can  only  @AliasIO  tell

2022-06-15 11:33 UTC, kazirahiv commented
no problem, I made the changes to cat 19 and requires nopCommerce @nurbek91

2022-06-20 04:44 UTC, merged

2022-06-20 04:44 UTC, AliasIO commented
Thank you!

2022-06-20 22:07 UTC, rockeynebhwani commented
@AliasIO @kazirahiv - We are missing 'nopStation.png'.