Add Notion Detection
wappalyzer/wappalyzer pull request #6415
Opened 2022-06-22 06:29 UTC by ysm0622

website:
- https://notion.so

examples: 
- https://www.notion.so/Notion-Community-04f306fbf59a413fae15f42e2a1ab029
- https://www.notion.so/sablecard/Sable-is-Hiring-472678e95a374c9cb5040252409a0714

2022-06-25 17:19 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
Needs minor updates to bring it to perfection

additional examples:
https://xuebin.me/
https://slahser.com/

2022-06-25 17:19 UTC, nurbek91 commented on src/technologies/n.json
> +    "description": "The all-in-one workspace — for notes, tasks, wikis, and databases.",
"description": "Notion is a collaboration platform with modified Markdown support that integrates kanban boards, tasks, wikis, and database.",

2022-06-25 17:19 UTC, nurbek91 commented on src/technologies/n.json
> +    "icon": "Notion.svg",
32x32
[Notion.svg.zip](https://github.com/wappalyzer/wappalyzer/files/8985263/Notion.svg.zip)

2022-06-26 05:32 UTC, ysm0622 commented
@nurbek91 Thanks! [a3a00b8](https://github.com/wappalyzer/wappalyzer/pull/6415/commits/a3a00b86025245ed717d455991182efbbc44fa04)

2022-06-26 12:52 UTC, nurbek91 approved these changes
thanks mate!!!

2022-06-26 22:43 UTC, merged