add Webzie.com / page builder
wappalyzer/wappalyzer pull request #6419
Opened 2022-06-24 23:16 UTC by RivierGrullon

## website
https://www.webzie.com/

### examples
https://www.dogs-cats.co.il/
https://www.chabad-judaica.com/
https://www.smilephone.co.il/
https://www.toys-express.co.il/
https://www.pashutrihut.co.il/
https://www.first-sport.co.il/
https://www.avinary-pro.com/
https://www.holylandlegacy.co.il/
https://www.deal-shop.co.il/
https://www.decoclick.co.il/
https://www.thebigmall.co.il/
https://www.anak-rihut.co.il/
https://www.pilotshop.co.il/
https://www.footballworld.co.il/
https://www.pumps4u.co.il/
https://www.emanueel.co.il/
https://www.at-work.co.il/
https://www.shakedsport.co.il/
https://www.zerimyafim.co.il/
https://www.yashir-la.co.il/

2022-06-24 23:19 UTC, RivierGrullon commented
The check failed for me locally because there's a missing icon for a different technology (not this - it's for nopStation).

2022-06-25 17:03 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!  
Fixed false-positive results   here #6420  that would interfere with this technology
Needs minor updates to bring it to perfection

2022-06-25 17:03 UTC, nurbek91 commented on src/technologies/w.json
> +      "generator": "Webzie\\.com Website Builder"
`"generator": "^Webzie\\.com\\sWebsite\\sBuilder$"`

2022-06-25 19:56 UTC, RivierGrullon commented
@nurbek91 this technology is "[webize.com](http://webize.com/)" and there is another tech called "[webzie.ir](http://webzie.ir/)"

2022-06-26 12:51 UTC, nurbek91 approved these changes
Hey mate , we can leave the name as Webzie without.com

2022-06-26 21:39 UTC, RivierGrullon commented
> Hey mate , we can leave the name as Webzie without.com

@nurbek91 done :)

2022-06-26 22:37 UTC, closed without merging

2022-06-26 22:44 UTC, RivierGrullon commented
@AliasIO this Technology is diferent than you commited #6420