Add substack Detection
wappalyzer/wappalyzer pull request #6491
Opened 2022-07-08 07:52 UTC by ysm0622

website:
- http://substack.com/

examples:
- https://cloudgeek.substack.com/
- https://www.notboring.co/
- https://on.substack.com/
- https://news.impossible.finance/
- https://newsletter.pragmaticengineer.com/

2022-07-13 20:05 UTC, nurbek91 requested changes
Hey mate. thanks for PR. just need some additional info and replace icon

2022-07-13 20:05 UTC, nurbek91 commented on src/technologies/s.json
> +  "substack": {
Substack instead substack?

2022-07-13 20:05 UTC, nurbek91 commented on src/technologies/s.json
> +    "headers": {
desc: "Substack is an American online platform that provides publishing, payment, analytics, and design infrastructure to support subscription newsletters."

2022-07-13 20:05 UTC, nurbek91 commented on src/technologies/s.json
> +    "icon": "substack.png",
[Substack.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9105653/Substack.svg.zip)
svg icon

2022-07-13 20:05 UTC, nurbek91 commented on src/technologies/s.json
> +    "icon": "substack.png",
As of 2020, the minimum fee for a subscription was $5/month or $30/year, and Substack usually takes a 10 percent fee from subscription payments.

 "pricing": [
      "payg"
    ],

2022-07-14 04:48 UTC, ysm0622 commented on src/technologies/s.json
> +  "substack": {
[3d0a102](https://github.com/wappalyzer/wappalyzer/pull/6491/commits/3d0a10278d0d940780c6ffb93ce64e1ce9c9432f)

2022-07-14 04:48 UTC, ysm0622 commented on src/technologies/s.json
> +    "headers": {
[6e2b1e2](https://github.com/wappalyzer/wappalyzer/pull/6491/commits/6e2b1e29c31a6fa2ff00e75791d63a757f3b70e9)

2022-07-14 04:48 UTC, ysm0622 commented on src/technologies/s.json
> +    "icon": "substack.png",
[a40e44f](https://github.com/wappalyzer/wappalyzer/pull/6491/commits/a40e44f58e54b301309cd67e9073e8bd2cfd9574)

[3486f31](https://github.com/wappalyzer/wappalyzer/pull/6491/commits/3486f311140a3c2c3ce0d2cefb4b63015ae2b9e1)

2022-07-14 04:48 UTC, ysm0622 commented
Thank you for review! 🙏🏻

2022-07-17 18:43 UTC, nurbek91 approved these changes
Thanks mate!!

2022-07-20 23:30 UTC, merged