Add instantgeo.info
wappalyzer/wappalyzer pull request #6492
Opened 2022-07-11 23:34 UTC by azeemhassni

This PR adds instantgeo.info to the list of technologies, this is my first contribution to this repo I'm happy to hear any feedback if I'm doing anything wrong. :)

2022-07-13 20:20 UTC, nurbek91 requested changes

2022-07-13 20:20 UTC, nurbek91 commented on src/technologies/i.json
> +    "implies": [],
"implies": [], 
Can be skipped if there is nothing to write there

2022-07-13 20:20 UTC, nurbek91 commented on src/technologies/i.json
> +    "description": "InstantGeo is a service that provides IP Geolocation to web pages",
"description": "InstantGeo is a service that provides IP geolocation to web pages.",

2022-07-13 20:20 UTC, nurbek91 commented on src/technologies/i.json
> +    "icon": "instantgeo.svg",
"icon": "instantgeo.svg", - >  "icon": "InstantGeo.svg",

2022-07-13 20:20 UTC, nurbek91 commented on src/technologies/i.json
> +    "description": "InstantGeo is a service that provides IP Geolocation to web pages",
[InstantGeo.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9105772/InstantGeo.svg.zip)
32x32

2022-07-13 20:22 UTC, nurbek91 commented
Hey mate, thanks for PR!!
Everything looks great. Changes are required simply to the style. 
It is also one of the requirements to attach examples(3-4 links if possible)

2022-07-14 20:30 UTC, azeemhassni commented on src/technologies/i.json
> +    "implies": [],
Removed it in my recent commit, thanks for pointing it out.

2022-07-14 20:31 UTC, azeemhassni commented on src/technologies/i.json
> +    "description": "InstantGeo is a service that provides IP Geolocation to web pages",
Updated and the description should be as suggested now.

2022-07-14 20:32 UTC, azeemhassni commented on src/technologies/i.json
> +    "icon": "instantgeo.svg",
Makes sense, so the icon name should exactly match the technology/app name. I have updated it and made sure the SVG rendering size is 32x32 px.

2022-07-17 18:44 UTC, nurbek91 approved these changes
Thanks mate!!

2022-07-20 23:43 UTC, merged