Add qiankun technology
wappalyzer/wappalyzer pull request #6530
Opened 2022-07-22 12:55 UTC by kuitos

## website
https://qiankun.umijs.org/

## github repo
https://github.com/umijs/qiankun

## examples
Sorry about the missing of examples, as most of the time this technology is used in enterprise, who are unaccessible from outside the company.

2022-07-22 13:03 UTC, kuitos commented
Already tested it locally, wish to be merged😄
![image](https://user-images.githubusercontent.com/5206843/180444855-ab38e4dc-af15-4122-9109-9fdb691a79a2.png)

2022-07-22 14:45 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
Small updates required

2022-07-22 14:45 UTC, nurbek91 commented on src/technologies/q.json
> +    },
we can add also js 

```
"js": {
      "qiankun.loadMicroApp": ""
    },
```

example https://www.medsci.cn/

2022-07-22 14:45 UTC, nurbek91 commented on src/technologies/q.json
> +    "icon": "qiankun.svg",
[qiankun.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9168631/qiankun.svg.zip)
32x32

2022-07-22 14:45 UTC, nurbek91 commented on src/technologies/q.json
> +      "div[id^=__qiankun_]": {
`"div[id^=__qiankun_]":`

`"div[id^='__qiankun_']":`

2022-07-22 15:25 UTC, kuitos commented on src/technologies/q.json
> +      "div[id^=__qiankun_]": {
Are these two not equivalent?

2022-07-22 15:30 UTC, kuitos commented on src/technologies/q.json
> +    "icon": "qiankun.svg",
done

2022-07-22 15:34 UTC, kuitos commented on src/technologies/q.json
> +    },
That might not be accurate, normally we would not attach qiankun to a global variable.
But the dom selector must be accurate.

2022-07-22 15:38 UTC, kuitos commented on src/technologies/q.json
> +      "div[id^=__qiankun_]": {
Added the single quotes to keep consistency with others, thanks for your quick response~

2022-07-22 16:50 UTC, kuitos commented on src/technologies/q.json
> +    "scripts": "__POWERED_BY_QIANKUN__",
Added a source code detection rule, could you pls donate some times to review it? @nurbek91

2022-07-22 19:16 UTC, nurbek91 commented on src/technologies/q.json
> +    "scripts": "__POWERED_BY_QIANKUN__",
Hey @kuitos ,
This option is less resource-intensive parameter
```
"js": {
      "qiankun.loadMicroApp": ""
    },
```

**dom** and **scripts** the most resource-intensive parameters.
From the technical side, everything looks correct.

But let's leave the decision @AliasIO , this is where my powers end.

2022-07-26 09:05 UTC, kuitos commented on src/technologies/q.json
> +    "scripts": "__POWERED_BY_QIANKUN__",
> This option is less resource-intensive parameter

Yes it is, but it‘s not common usage, so it's not very accurate.

@AliasIO Could you pls donate some time to review this pr?

2022-07-26 23:47 UTC, merged

2022-07-26 23:47 UTC, AliasIO commented
Thanks!

2022-08-23 02:11 UTC, kuitos commented
Not to rush you, just wondering when we could release a new version for chrome extension? @AliasIO 😀

2022-08-24 21:49 UTC, AliasIO commented
Today :)