Add TripleWhale
wappalyzer/wappalyzer pull request #6603
Opened 2022-08-04 22:02 UTC by Overload119

2022-08-05 02:53 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
Needs an update to perfect your PR

2022-08-05 02:53 UTC, nurbek91 commented on src/technologies/t.json
> +    "html": "triplewhale-pixel.web.app\/triplepx.txt",
The html parameter is resource intensive and can be used when all other methods are not possible.
In your case, we can replace it with 
 "xhr": "triplewhale-pixel\\.web\\.app",

2022-08-05 02:53 UTC, nurbek91 commented on src/technologies/t.json
> +    "icon": "triplewhale.png",
Preferred icon format is svg with size 32x32
[Triple Whale.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9264825/Triple.Whale.svg.zip)

2022-08-05 02:53 UTC, nurbek91 commented on src/technologies/t.json
> +  "TripleWhale": {
The correct name of technologies is two words written separately? Triple Whale

We can add description:

`"description": "Triple Whale is a mobile app used by ecommerce businesses to track profits, blended ROAS, LTV, and much more, integrating into a single easy-to-use mobile app.",`

pricing:
```
"pricing": [
      "mid",
      "recurring"
    ],
```

2022-08-05 15:15 UTC, Overload119 commented on src/technologies/t.json
> +  "TripleWhale": {
That description is not quite right - Triple Whale has an app, but it's not known as that.
I will pull a description from Crunchbase.

2022-08-11 23:32 UTC, merged

2022-08-11 23:32 UTC, AliasIO commented
Thanks!