Add ASP.NET Boilerplate / web-framework
wappalyzer/wappalyzer pull request #6631
Opened 2022-08-09 07:08 UTC by m-aliozkaya

An open source project 10.5K star
https://github.com/aspnetboilerplate/aspnetboilerplate

### Website
https://aspnetboilerplate.com/

### Examples
https://app.workiom.com/

https://aspnetzero.com/

https://aspnetboilerplate.com/

2022-08-10 04:59 UTC, nurbek91 requested changes
Hey mate thanks for PR!!
Requires minor changes to perfect your request

2022-08-10 04:59 UTC, nurbek91 commented on src/technologies/a.json
> +    "icon": "aspnetboilerplate.png",
32x32 
![ASP NET Boilerplate](https://user-images.githubusercontent.com/3456008/183818445-32d8027f-056c-4597-871f-f2901c3e844b.png)

2022-08-10 04:59 UTC, nurbek91 commented on src/technologies/a.json
> +    "scripts" : "abp.appPath",
this can be replaced with less resource intensive variant

```
"js": {
      "abp.toAbsAppPath": "",
      "abp.localization": ""
    },

```

2022-08-10 04:59 UTC, nurbek91 commented on src/technologies/a.json
> +    "text": "\\ASP.NET Boilerplate\\b",
the text parameter is resource-intensive and is used in exceptional cases when it is impossible to determine the technology in another way.
If there are such websites, please share the link.

There are also traces that can be added additionally without worrying about resources.
```
"cookies": {
      "Abp.Localization.CultureName": ""
    },

```

2022-08-10 06:36 UTC, m-aliozkaya commented
Thank you for helping so quickly, I'm doing the necessary changes.

2022-08-11 11:00 UTC, nurbek91 approved these changes
Thanks!!

2022-08-11 23:28 UTC, merged

2022-08-11 23:28 UTC, AliasIO commented
Thanks!