Add oopy detection
wappalyzer/wappalyzer pull request #6720
Opened 2022-08-31 07:48 UTC by ysm0622

website:
- https://oopy.us/
- https://oopy.io/

examples:
- https://tosspayments-dev.oopy.io/
- https://jobs.class101.net/
- https://www.opgg.team/
- https://careers.amazevr.com/
- https://watcha.team/
- https://woowahan.oopy.io/
-

2022-08-31 20:48 UTC, nurbek91 requested changes
Hey mate, thanks for your PR!!!
Requires cosmetic updates to bring to the ideal

2022-08-31 20:48 UTC, nurbek91 commented on src/technologies/o.json
> +    "icon": "oopy.png",
32x32
![Oopy](https://user-images.githubusercontent.com/3456008/187778626-6555a372-a2a2-494c-b329-4d4617f1e30e.png)

2022-08-31 20:48 UTC, nurbek91 commented on src/technologies/o.json
> +  "oopy": {
Let's write the names of technologies with a capital letter, just like in the descriptions

2022-09-01 02:06 UTC, ysm0622 commented on src/technologies/o.json
> +  "oopy": {
[609b56c](https://github.com/wappalyzer/wappalyzer/pull/6720/commits/609b56c9c6896a03b4dbdf5b7f8e4ccf9fdf442f)

2022-09-01 03:20 UTC, merged

2022-09-01 03:20 UTC, AliasIO commented
Thanks!