Update Appian
wappalyzer/wappalyzer pull request #6721
Opened 2022-08-31 15:32 UTC by t-miller

1. Updated logo to new version
2. Updated regex to remove `/suite/`, matching pattern shown in [Appian's docs](https://docs.appian.com/suite/help/22.3/Embedded_Interfaces.html#load-appian's-web-components)

2022-08-31 20:58 UTC, nurbek91 requested changes
Hey mate, thanks for your PR!!!
I could not find examples, there are no results in the Wappalyzer database
Do you have any links I would like to look at possible additional traces
https://www.wappalyzer.com/technologies/paas/appian/

2022-08-31 20:58 UTC, nurbek91 commented on src/technologies/a.json
>      "icon": "Appian.png",
preferred format ымп
[Appian.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9464940/Appian.svg.zip)

2022-08-31 20:58 UTC, nurbek91 commented on src/technologies/a.json
> +    "scriptSrc": "tempo/ui/sail-client/embeddedBootstrap.nocache.js",
`"scriptSrc": "tempo/ui/sail-client/embeddedBootstrap\\.nocache\\.js",`

2022-09-01 14:49 UTC, t-miller commented
> Hey mate, thanks for your PR!!! I could not find examples, there are no results in the Wappalyzer database Do you have any links I would like to look at possible additional traces https://www.wappalyzer.com/technologies/paas/appian/

Hey @nurbek91,

I stood up a Community site and provisioned a user with basic permissions that should allow you to view the detection - I'll inactivate the user later.

site: `https://xloi.appian.community/suite/sites/net-zero-carbon/page/overview`
username: `test.user`
pasword: `test123`

2022-09-01 19:32 UTC, nurbek91 commented
Hey @t-millerm thanks!!! We can add this in addition, maybe it will help 
```
"js": {
      "APPIAN": "",
      "Appian": "",
      "webpackJsonpAppian": "",
      "_APPIAN_PROXIES_INITIALIZED": ""
    },
```

2022-09-02 17:30 UTC, nurbek91 approved these changes
thanks mate!!

2022-09-26 22:01 UTC, merged

2022-09-26 22:01 UTC, AliasIO commented
Thanks!