Add NexusPIPE / cdn
wappalyzer/wappalyzer pull request #6728
Opened 2022-09-01 21:33 UTC by Jack-Bailey

2022-09-01 21:34 UTC, Jack-Bailey commented
Original issue: #6547

2022-09-02 17:58 UTC, nurbek91 requested changes
Hey mate thanks for PR!!!
need small changes

2022-09-02 17:58 UTC, nurbek91 commented on src/technologies/n.json
> +    "icon": "NexusPIPE.png",
32x32
![NexusPIPE](https://user-images.githubusercontent.com/3456008/188210492-197b169d-9951-411a-ab17-88aae8c06a46.png)

2022-09-02 17:58 UTC, nurbek91 commented on src/technologies/n.json
> +      31
We can add a  Security category 16

2022-09-02 17:58 UTC, nurbek91 commented on src/technologies/n.json
> +    "description": "NexusPIPE is a ADC & DDoS mitigation Company.",
NexusPIPE is a ADC and DDoS mitigation company.

2022-09-02 18:37 UTC, Jack-Bailey commented
No problem - Added your changes

2022-09-26 22:10 UTC, merged

2022-09-26 22:10 UTC, AliasIO commented
Thanks!