Add NextUI Detection
wappalyzer/wappalyzer pull request #6752
Opened 2022-09-09 13:17 UTC by ysm-dev

website:
- https://nextui.org

examples:
- https://chartbrew.com/
- https://learnfrontend.io/
- https://spotwitchy.vercel.app/
- https://www.microdiscount.website/
- https://scriptbar-snippets.tryapp.us/

2022-09-12 19:15 UTC, nurbek91 requested changes
Hey mate, thanks for your PR!!!
Minor updates needed to perfect your request

2022-09-12 19:15 UTC, nurbek91 commented on src/technologies/n.json
> +    "icon": "NextUI.png",
It is advisable to use svg format for icons
[NextUI.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9551075/NextUI.svg.zip)

2022-09-12 19:15 UTC, nurbek91 commented on src/technologies/n.json
> +    "description": "NextUI is beautiful, fast and modern React UI Library.",
Probably it will be necessary to write a more technical description than an advertising one.

2022-09-12 19:15 UTC, nurbek91 commented on src/technologies/n.json
> +    "dom": "[class^='nextui-c-']",
Is it possible to check a specific tag or several to avoid performance issues?

2022-09-13 04:49 UTC, ysm-dev commented on src/technologies/n.json
> +    "icon": "NextUI.png",
[29541aa](https://github.com/wappalyzer/wappalyzer/pull/6752/commits/29541aa0f88bc0e862f14978ec923649bacaa902)

2022-09-13 04:50 UTC, ysm-dev commented on src/technologies/n.json
> +    "description": "NextUI is beautiful, fast and modern React UI Library.",
[ee44e23](https://github.com/wappalyzer/wappalyzer/pull/6752/commits/ee44e23f2a241b43398ee5a8f1e1e203b9885bae)

2022-09-13 04:51 UTC, ysm-dev commented on src/technologies/n.json
> +    "dom": "[class^='nextui-c-']",
[b15b164](https://github.com/wappalyzer/wappalyzer/pull/6752/commits/b15b164d05d7ba592d82a3f315a6ea5e33bbd690)

2022-09-14 11:09 UTC, nurbek91 approved these changes

2022-09-26 22:24 UTC, merged

2022-09-26 22:24 UTC, AliasIO commented
Thanks!