Add UnoCSS Detection
wappalyzer/wappalyzer pull request #6753
Opened 2022-09-09 14:04 UTC by ysm-dev

website:
- https://uno.antfu.me/

examples:
- https://weak-rabbit-42.deno.dev/
- https://dash.deno.com/
- https://vitesse.netlify.app/
- https://pdf.ruleplaying.com/
- https://springue.github.io/demo-playground/

2022-09-12 19:26 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!
Need small updates maybe

2022-09-12 19:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "icon": "UnoCSS.svg",
32x32
[UnoCSS.svg.zip](https://github.com/wappalyzer/wappalyzer/files/9551128/UnoCSS.svg.zip)

2022-09-12 19:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "icon": "UnoCSS.svg",
"oss": true,

2022-09-12 19:26 UTC, nurbek91 commented on src/technologies/u.json
> +    "css": "--un-(?:rotate|translate|space-x|text-opacity|border-opacity)",
![image](https://user-images.githubusercontent.com/3456008/189737998-5ff7b85f-936e-4dc2-9d9c-5a5bfd1afb5e.png)

```
 "dom": {
      "style[data-unocss]": {
        "attributes": {
          "data-unocss": "([\\d\\.]+)\\;version:\\1"
        }
      }
    },
```

2022-09-13 04:55 UTC, ysm-dev commented on src/technologies/u.json
> +    "icon": "UnoCSS.svg",
[b60f702](https://github.com/wappalyzer/wappalyzer/pull/6753/commits/b60f702b3701efb278d90828419c35e16a657b4c)

[f35e147](https://github.com/wappalyzer/wappalyzer/pull/6753/commits/f35e147a247c730b9e8e4cdc054da303f81604e2)

2022-09-13 04:55 UTC, ysm-dev commented on src/technologies/u.json
> +    "css": "--un-(?:rotate|translate|space-x|text-opacity|border-opacity)",
[79fcc72](https://github.com/wappalyzer/wappalyzer/pull/6753/commits/79fcc727045d861ccdcde5560fab09ad0851e433)

2022-09-14 11:10 UTC, nurbek91 approved these changes

2022-09-26 22:25 UTC, merged