Add ABP.IO / web-framework
wappalyzer/wappalyzer pull request #6761
Opened 2022-09-14 11:22 UTC by m-aliozkaya

ABP framework is the successor of the open source [ASP.NET Boilerplate](https://aspnetboilerplate.com/) framework. ABP framework is also open source and free. 

See https://github.com/abpframework/abp

### Website
https://abp.io/

### Examples
https://abp.io/
https://www.eshoponabp.com/
https://www.openeventhub.com/

2022-09-15 06:29 UTC, nurbek91 requested changes
Hey mate thanks for PR!!
Need some cosmetic changes

2022-09-15 06:29 UTC, nurbek91 commented on src/technologies/a.json
> +    "icon": "abp.png",
32x32 svg
![ABP IO](https://user-images.githubusercontent.com/3456008/190330383-9ad638e8-b40a-4fe7-a6d6-55837f62db96.svg)

2022-09-15 06:29 UTC, nurbek91 commented on src/technologies/a.json
> +  "ABP.IO": {
ABP Framework instead ABP.IO maybe ?

2022-09-15 06:30 UTC, nurbek91 commented on src/technologies/a.json
> -      "abp.localization": "",
Are you sure about the fingerprints? Since I don't know all the details

2022-09-19 04:47 UTC, m-aliozkaya commented on src/technologies/a.json
> -      "abp.localization": "",
Yes, I tested it in my local version.

2022-09-19 04:48 UTC, m-aliozkaya commented on src/technologies/a.json
> +  "ABP.IO": {
Thank you

2022-09-26 09:59 UTC, nurbek91 reviewed
Thank you, I can't say anything about the fingerprints, I'll trust your knowledge

2022-09-26 10:33 UTC, m-aliozkaya commented
Thank you very much 🙏

2022-09-26 22:31 UTC, merged

2022-09-26 22:31 UTC, AliasIO commented
Thanks!