Add Imgix detection
wappalyzer/wappalyzer pull request #6862
Opened 2022-10-14 10:28 UTC by charisTheo

This PR adds [Imgix](https://imgix.com/) (Digital Asset CDN) detection.

Some example pages that use Imgix for testing:

1. https://www.producthunt.com/posts/omnisearch
2. https://www.kickstarter.com/projects/keyitechnology/meet-loona-the-petbot-you-will-fall-in-love
3. https://imgix.com/

2022-10-14 18:21 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!
Need small changes

2022-10-14 18:21 UTC, nurbek91 commented on src/technologies/i.json
> +      "low",
mid instead low

2022-10-14 18:21 UTC, nurbek91 commented on src/technologies/i.json
> +    "icon": "Imgix.svg",
![Imgix](https://user-images.githubusercontent.com/3456008/195914458-ee5ddcbe-02ea-45d0-ba5b-ca0b4f7334b5.svg)
32x32

2022-10-14 18:21 UTC, nurbek91 commented on src/technologies/i.json
> +    "description": "Imgix transforms, optimizes, and intelligently caches your entire asset library for faster pages, higher engagement, and a simpler workflow.",
Imgix is a visual media platform for managing, processing, rendering, optimising and delivering your existing images.

2022-10-17 10:07 UTC, charisTheo commented
Thanks @nurbek91! I've made the changes :)

2022-10-17 10:09 UTC, nurbek91 approved these changes
:heart_hands:

2022-10-17 22:01 UTC, merged

2022-10-17 22:01 UTC, AliasIO commented
Thanks!