Add visx
wappalyzer/wappalyzer pull request #6955
Opened 2022-11-02 16:25 UTC by ysm-dev

https://airbnb.io/visx/

- https://airbnb.io/visx/zoom-i
- https://donate.data2thepeople.org/
- https://augora.fr/statistiques
- https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=BarSeries%20--%20no%20axes&full=0&addons=0&stories=1&panelRight=0
- https://tokenizedbtc.info/
- https://eft.monster/

2022-11-03 17:13 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!

2022-11-03 17:13 UTC, nurbek91 commented on src/technologies/v.json
> +    "icon": "Visx.png",
![Visx](https://user-images.githubusercontent.com/3456008/199786884-67e8a3ba-24cd-4719-98ad-6f71a3bbb359.svg)

2022-11-03 17:13 UTC, nurbek91 commented on src/technologies/v.json
> +    "description": "visx a collection of expressive, low-level visualization primitives for React.",
`"description": "Visx is a collection of React-based data visualisation tools developed by Airbnb. ",`

2022-11-03 18:11 UTC, nurbek91 commented on src/technologies/v.json
> +      "[class^='vx-(?:group|line|linepath|area-closed|axis|bar|tooltip-portal|glyph|glyph-triangle']"
This is inside the **dom** parameter in my opinion does not work
`[class^='vx-(?:group|line|linepath|area-closed|axis|bar|tooltip-portal|glyph|glyph-triangle']`

it look too wide and resource intensive 
`[class^='visx-'] `

maybe just replace with this?
g[class^='visxgroup-'] ?

2022-11-04 04:11 UTC, ysm-dev commented on src/technologies/v.json
> +    "icon": "Visx.png",
[1aeee5e](https://github.com/wappalyzer/wappalyzer/pull/6955/commits/1aeee5eeab3d1221deafea8279a0bcb11e1eb215)

2022-11-04 04:11 UTC, ysm-dev commented on src/technologies/v.json
> +    "description": "visx a collection of expressive, low-level visualization primitives for React.",
[70657ca](https://github.com/wappalyzer/wappalyzer/pull/6955/commits/70657ca140901187fd91db0ba42632e2096aa31e)

2022-11-04 04:11 UTC, ysm-dev commented on src/technologies/v.json
> +      "[class^='vx-(?:group|line|linepath|area-closed|axis|bar|tooltip-portal|glyph|glyph-triangle']"
[a5f2c9d](https://github.com/wappalyzer/wappalyzer/pull/6955/commits/a5f2c9d10862a875c1b9e2f1fe0aa4d7e83fc37b)

2022-11-04 13:59 UTC, nurbek91 requested changes

2022-11-04 13:59 UTC, nurbek91 commented on src/technologies/v.json
> +    "dom": [
Let's do this so that our code covers all the examples that you provided. Before that, I tested the first two links and at the end I noticed that there is another pattern
```
"dom": {
      "g.visx-group,g.vx-group": {
        "attributes": {
          "class": "(?:v(?:is)?x)-group"
        }
      }
    },
```

2022-11-05 08:16 UTC, ysm-dev commented on src/technologies/v.json
> +    "dom": [
[74a399d](https://github.com/wappalyzer/wappalyzer/pull/6955/commits/74a399d949446f50d6ef19af84c3a9a1242f142c)

2022-11-06 21:41 UTC, merged

2022-11-06 21:42 UTC, AliasIO commented
Thanks!