Add Recharts
wappalyzer/wappalyzer pull request #6956
Opened 2022-11-02 16:33 UTC by ysm-dev

https://recharts.org/

- https://recharts.org/
- https://recharts.org/en-US/examples

2022-11-03 16:54 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!

2022-11-03 16:54 UTC, nurbek91 commented on src/technologies/r.json
> +      "[class^=recharts-]"
Maybe replace with this 
examples:
https://coinloop.io/
https://coinmetro.com/
https://www.uvocorp.com/
```
"dom": {
      "div > div > svg.recharts-surface": {
        "attributes": {
          "class": ""
        }
      }
    },
```

Hey @AliasIO ,  Does this design help with broad matches and does it improve performance?

2022-11-03 16:54 UTC, nurbek91 commented on src/technologies/r.json
> +    "description": "Recharts is a Redefined chart library built with React and D3.",
` "description": "Recharts is a component-based charting library, which is exclusively built for React applications."`

`"implies": "React",` ?

2022-11-03 16:54 UTC, nurbek91 commented on src/technologies/r.json
> +    "icon": "Recharts.png",
I drew two versions of the icon. One is more readable but doesn't match the actual icon. In general, there is no such icon there, just text. Large text is not very readable. Generally choose what suits  best.
![Recharts1](https://user-images.githubusercontent.com/3456008/199784321-bcde97f8-ea4d-4eb3-9259-b918a275cd3e.svg)
![Recharts](https://user-images.githubusercontent.com/3456008/199784339-5d0abf7d-38d6-4a65-a1f7-a8214664f6cb.svg)

2022-11-06 21:51 UTC, AliasIO commented on src/technologies/r.json
> +      "[class^=recharts-]"
Yes it does, although the original is ok. As long as the number of elements that match the pattern is limited.

2022-11-09 13:26 UTC, ysm-dev commented on src/technologies/r.json
> +    "description": "Recharts is a Redefined chart library built with React and D3.",
[3c1e744](https://github.com/wappalyzer/wappalyzer/pull/6956/commits/3c1e744ee53f74da981b400ded14d06d8195c084)
[f54528c](https://github.com/wappalyzer/wappalyzer/pull/6956/commits/f54528cbbf2195c0223c46bda8da0820b42a56bf)

2022-11-09 13:26 UTC, ysm-dev commented on src/technologies/r.json
> +    "icon": "Recharts.png",
[aff59ee](https://github.com/wappalyzer/wappalyzer/pull/6956/commits/aff59ee85cc75fb63eed5b97d669fc52bc4ba834)

2022-11-10 20:51 UTC, nurbek91 approved these changes
Thanks mate!!

2022-11-14 23:34 UTC, merged