Add GLPI detection
wappalyzer/wappalyzer pull request #6961
Opened 2022-11-03 15:33 UTC by Darkiros

Add GLPI detection.
If version is `>=10`, version is set to 10 because since 10.0 it is hard to know exactly the version.

Here is the github project of GLPI : https://github.com/glpi-project/glpi

2022-11-03 16:24 UTC, nurbek91 requested changes
Hey mate, thanks for PR!! Need some updates to bring ideal and resource-intensive.
Examples:
http://mquest.com.br/
http://veapp.net/

Are there any examples where versions above 10 are used?

2022-11-03 16:24 UTC, nurbek91 commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
```
 "dom": {
      "input[name='_glpi_csrf_token']": {
        "attributes": {
          "name": ""
        }
      },
      "div[id*='footer-login'] > a": {
          "text": "GLPI\\sversion\\s+([\\d\\.]+)\\;version:\\1"
      }
    },
```

2022-11-03 16:24 UTC, nurbek91 commented on src/technologies/g.json
> +        13
Maybe add CRM category but i am not sure

2022-11-03 16:24 UTC, nurbek91 commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
Maybe we can add pricing also 
https://glpi-project.org/prices/
```
"pricing": [
      "mid",
      "recurring"
    ],
```

2022-11-03 16:32 UTC, Darkiros commented
> Hey mate, thanks for PR!! Need some updates to bring ideal and resource-intensive. Examples: http://mquest.com.br/ http://veapp.net/
> 
> Are there any examples where versions above 10 are used?

Hi, here you can find GLPI versions above 10:
https://glpi.webcom-info.com/

2022-11-03 16:45 UTC, Darkiros commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
```
"dom": {
      "input[name='_glpi_csrf_token']": {
        "attributes": {
          "name": ""
        }
      },
      "div[id*='footer-login'] > a": {
          "text": "GLPI\\sversion\\s+([\\d\\.]+)\\;version:\\1"
      }
    },
```
I don't know why but with `dom` section it doesn't seem to work.

2022-11-03 16:56 UTC, Darkiros commented on src/technologies/g.json
> +        13
Yes, I think it might fits too.

2022-11-03 17:18 UTC, nurbek91 commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
Hm strange. I tested on versions below 10 and everything worked there (the part with checking versions and just checking the input). Now I will look at your links above 10 versions

2022-11-03 17:25 UTC, nurbek91 commented
> > Hey mate, thanks for PR!! Need some updates to bring ideal and resource-intensive. Examples: http://mquest.com.br/ http://veapp.net/
> > Are there any examples where versions above 10 are used?
> 
> Hi, here you can find GLPI versions above 10: https://glpi.webcom-info.com/ https://glpi.picinformatique.com/ https://glpi.sqli.com/

Above 10 versions are defined without regular expressions by these traces

```
"js": {
      "glpiUnsavedFormChanges": ""
    },
"meta": {
      "glpi:csrf_token": ""
    },
```

2022-11-03 17:51 UTC, Darkiros commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
```
 "div[id*='footer-login'] > a": {
          "text": "GLPI\\sversion\\s+([\\d\\.]+)\\;version:\\1"
      }
```
This one doesn't seem work on http://mquest.com.br/ for me.

2022-11-03 18:55 UTC, nurbek91 commented on src/technologies/g.json
> +        "<input[^>]*name=\\D_glpi_csrf_token\\D"
> ```
>  "div[id*='footer-login'] > a": {
>           "text": "GLPI\\sversion\\s+([\\d\\.]+)\\;version:\\1"
>       }
> ```
> 
> This one doesn't seem work on http://mquest.com.br/ for me.

For now, you can make other changes. I'll test again in that case tomorrow mate

2022-11-04 13:45 UTC, nurbek91 requested changes
Tested, everything works.
Can you make it look like this?  need to remove the html and change the regex a bit
```
"GLPI": {
    "cats": [
        18,
        53
    ],
    "cpe": "cpe:2.3:a:glpi-project:glpi:*:*:*:*:*:*:*:* ",
    "description": "GLPI is an open-source IT Asset Management, issue tracking and service desk system.",
    "dom": {
      "input[name='_glpi_csrf_token']": {
        "attributes": {
          "name": ""
        }
      },
        "div[id='footer-login'] > a": {
            "text": "GLPI\\s+version\\s+([\\d\\.]+)\\;version:\\1"
        }
    },
    "js": {
        "glpiUnsavedFormChanges": ""
    },
    "meta": {
        "glpi:csrf_token": ""
    },
    "oss": true,
    "icon": "GLPI.png",
    "implies": "PHP",
    "pricing": [
        "mid",
        "recurring"
      ],
    "website": "https://glpi-project.org"   
  },
```

2022-11-04 14:03 UTC, Darkiros commented
> Tested, everything works. Can you make it look like this? need to remove the html and change the regex a bit
> 
> ```
> "GLPI": {
>     "cats": [
>         18,
>         53
>     ],
>     "cpe": "cpe:2.3:a:glpi-project:glpi:*:*:*:*:*:*:*:* ",
>     "description": "GLPI is an open-source IT Asset Management, issue tracking and service desk system.",
>     "dom": {
>       "input[name='_glpi_csrf_token']": {
>         "attributes": {
>           "name": ""
>         }
>       },
>         "div[id='footer-login'] > a": {
>             "text": "GLPI\\s+version\\s+([\\d\\.]+)\\;version:\\1"
>         }
>     },
>     "js": {
>         "glpiUnsavedFormChanges": ""
>     },
>     "meta": {
>         "glpi:csrf_token": ""
>     },
>     "oss": true,
>     "icon": "GLPI.png",
>     "implies": "PHP",
>     "pricing": [
>         "mid",
>         "recurring"
>       ],
>     "website": "https://glpi-project.org"   
>   },
> ```

It works for the dom, I missed something sorry.
But if we remove the html, we will only be able to detect the version 0.X.X of GLPI not 9.X.X for exemple.

2022-11-04 15:59 UTC, nurbek91 commented
> 9.X.X for exemple
Ah ok. can u share links i will take a look

2022-11-04 16:02 UTC, Darkiros commented
> > 9.X.X for exemple
> 
> Ah ok. can u share links i will take a look

Sure, this one for exemple:
https://glpi.vigians.com/

2022-11-04 16:39 UTC, nurbek91 commented
> > > 9.X.X for exemple
> > 
> > 
> > Ah ok. can u share links i will take a look
> 
> Sure, this one for exemple: https://glpi.vigians.com/ https://glpi.actuafilms.com/
We can add something like this, 
`"scriptSrc": "//glpi\\..+common\\.min\\.js\?v=([\\d\\.]+)\\;version:\\1",`
the main thing is to remove html and it is desirable not to use dom either.
Another question is can we specify requires: "Debian" ?

2022-11-07 08:52 UTC, Darkiros commented
> > > > 9.X.X for exemple
> > > 
> > > 
> > > Ah ok. can u share links i will take a look
> > 
> > 
> > Sure, this one for exemple: https://glpi.vigians.com/ https://glpi.actuafilms.com/
> 
> We can add something like this, `"scriptSrc": "//glpi\\..+common\\.min\\.js\?v=([\\d\\.]+)\\;version:\\1",` the main thing is to remove html and it is desirable not to use dom either. Another question is can we specify requires: "Debian" ?

Yes it works but it is quite restricted because this will only work on glpi.XX.XX domain names.

About debian, we can't specify it because GLPI can be installed everywhere, you just need PHP.

2022-11-08 17:10 UTC, nurbek91 approved these changes
Hey mate , thanks!

2022-11-09 07:58 UTC, Darkiros commented
> Hey mate , thanks!

Hi ! This is the final commit, I changed the regex to : 
`"scriptSrc": "//.*glpi.+common\\.min\\.js\\?v=(\\d+\\.\\d+\\.\\d+)\\;version:\\1",`
Because the last one matched with version >=10 and wrote a false number in version. Now it should be fixed.

2022-11-10 20:51 UTC, nurbek91 approved these changes

2022-11-14 23:36 UTC, merged

2022-11-14 23:36 UTC, AliasIO commented
Thanks!