added australian call tracking providers
wappalyzer/wappalyzer pull request #7036
Opened 2022-11-25 00:33 UTC by b3bb0

2022-11-25 08:03 UTC, b3bb0 commented
Fixes the regex... just tested them.

for testing **delacon**
 - https://www.vocus.com.au/

for testing **avanser**:
 - https://www.boq.com.au/

2022-11-25 14:12 UTC, nurbek91 requested changes
### Hey mate, thanks for PR!! 
Need updates to bring perfect
### Avanser examples:
https://geckologistics.com.au/
https://maxmyprofit.com.au/
https://penguins.org.au/
https://www.clubpinerivers.com.au/
### Delacon examples:
https://www.heritage.com.au/
https://www.villagehouse.jp/en/
https://www.shannons.com.au/
https://www.stratco.com.au/

2022-11-25 14:12 UTC, nurbek91 commented on src/technologies/a.json
> +    "description": "Maximise Your Call Value With Call Tracking, Insights Solutions. Track Every Call, Enable Your Business to Make Better-informed Decisions. Avanser is a mediocre call tracking prov
`"description": "Avanser is the leading call tracking technology company in the Asia Pacific Region."`

2022-11-25 14:12 UTC, nurbek91 commented on src/technologies/a.json
> +    "scriptSrc": "avanser\\.com/(aa|static)",
instead scriptSrc we can use js
```
"js": {
      "AvanserCore": "",
      "AvanserOptions": ""
    },
```

2022-11-27 13:38 UTC, b3bb0 commented on src/technologies/a.json
> +    "description": "Maximise Your Call Value With Call Tracking, Insights Solutions. Track Every Call, Enable Your Business to Make Better-informed Decisions. Avanser is a mediocre call tracking prov
it's their claim. they are not the leaders

2022-11-27 17:59 UTC, nurbek91 commented on src/technologies/a.json
> +    "description": "Maximise Your Call Value With Call Tracking, Insights Solutions. Track Every Call, Enable Your Business to Make Better-informed Decisions. Avanser is a mediocre call tracking prov
No problem. I couldn't find less promotional text  ;)

2022-11-28 01:59 UTC, b3bb0 commented
Updated the code as suggested from @nurbek91 comments

2022-11-28 11:50 UTC, nurbek91 approved these changes

2022-11-30 13:58 UTC, nurbek91 approved these changes
Everything looks great!!

2022-11-30 14:00 UTC, nurbek91 commented on src/technologies/d.json
> +    "scriptSrc": "plavxml\\.com",
We can leave both if there are examples of websites where js objects are missing but this file is present. Then it would make sense to leave both options

2022-11-30 20:34 UTC, merged