NextAuthjs Authentication detection added for Next.js
wappalyzer/wappalyzer pull request #7189
Opened 2022-12-09 13:20 UTC by dhavalveera

NextAuthjs Authentication is used for Next.js Web Apps

https://next-auth-example.vercel.app/

2022-12-09 15:00 UTC, ysm-dev commented
examples:
- https://sharegpt.com/
- https://photoshot.app/
- https://www.github-icons.com/
- https://drift.lol/
- https://ticket-booking-app-two.vercel.app/

2022-12-09 15:33 UTC, ysm-dev commented
run `npm run prettify` once.

2022-12-10 02:10 UTC, dhavalveera commented
> examples:
> 
> * https://sharegpt.com/
> * https://photoshot.app/
> * https://www.github-icons.com/
> * https://drift.lol/
> * https://ticket-booking-app-two.vercel.app/

Thanks for sharing a few examples where `NextAuth.js` has been used.

2022-12-10 11:04 UTC, nurbek91 requested changes
![NextAuth js](https://user-images.githubusercontent.com/3456008/206851850-78537b20-72e1-4427-a91b-78f8555b2fc7.png)

2022-12-11 15:11 UTC, nurbek91 requested changes

2022-12-11 15:11 UTC, nurbek91 commented on src/technologies/n.json
> +    ],
this can be removed,
freemium - only for those where there are still other tariffs
if oss=true then this block is generally not needed

2022-12-11 15:11 UTC, nurbek91 commented on src/technologies/n.json
> +    "scripts": "localStorage\\.getItem\\('nextauth.message'\\)",
I could not find this trace in the examples, can you tell me where to look at it.
If not critical, you can probably remove it. Cookies look stable at first glance

2022-12-12 01:56 UTC, dhavalveera commented on src/technologies/n.json
> +    "scripts": "localStorage\\.getItem\\('nextauth.message'\\)",
I tried the `localStroage` part, but it doesn't work, but this 
```"cookies": {
      "__Host-next-auth.csrf-token": ""
    },```

this cookie is working correctly

2022-12-12 01:57 UTC, dhavalveera commented on src/technologies/n.json
> +    ],
will remove this

2022-12-12 02:01 UTC, dhavalveera commented on src/technologies/n.json
> +    "scripts": "localStorage\\.getItem\\('nextauth.message'\\)",
removed `localStorage` script from code

2022-12-12 07:04 UTC, nurbek91 approved these changes

2022-12-13 23:06 UTC, merged