Clutch Widget Detection added
wappalyzer/wappalyzer pull request #7207
Opened 2022-12-15 03:48 UTC by dhavalveera

### technology requested [7203](https://github.com/wappalyzer/wappalyzer/issues/7203)

Vendor Site - https://clutch.co/

Category - Reviews, Widgets

**Example Sites:**

https://bluesoft.com/
https://www.xfive.co/

2022-12-15 08:59 UTC, dhavalveera reviewed
#7203

2022-12-15 09:52 UTC, nurbek91 requested changes
Hey mate, thanks for PR.Need to improve it

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    "scriptSrc": "https://widget.clutch.co/static/js/widget.js",
`"scriptSrc":  //widget\\.clutch\\.co/`

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    "description": "Ratings and reviews of leading IT, marketing, and business services companies. Clutch is your data-driven field guide for B2B buying and hiring decisions.",
`"description": "Clutch review widgets are stand-alone applications that you can embed on your website to show your dynamic ratings and reviews.",`

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "div[class*='clutch-widget'], div[data-url*='https://widget.clutch.co']",
This line can be removed

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "clutch.png",
svg
![Clutch](https://user-images.githubusercontent.com/3456008/207827764-0350eda3-4117-4506-aabf-f17d539adc2f.svg)

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    "website": "https://clutch.co/"
`"website": "https://clutch.co/content/add-review-widget-your-website"`

2022-12-15 09:52 UTC, nurbek91 commented on src/technologies/c.json
> +    ],
90
5

2022-12-15 10:04 UTC, dhavalveera commented on src/technologies/c.json
> +    "scriptSrc": "https://widget.clutch.co/static/js/widget.js",
done

2022-12-15 10:05 UTC, dhavalveera commented on src/technologies/c.json
> +    "dom": "div[class*='clutch-widget'], div[data-url*='https://widget.clutch.co']",
`"description"` needs to be removed?

2022-12-15 10:06 UTC, dhavalveera commented on src/technologies/c.json
> +    "icon": "clutch.png",
done

2022-12-15 10:06 UTC, dhavalveera commented on src/technologies/c.json
> +    "description": "Ratings and reviews of leading IT, marketing, and business services companies. Clutch is your data-driven field guide for B2B buying and hiring decisions.",
done

2022-12-15 10:08 UTC, dhavalveera commented on src/technologies/c.json
> +    "website": "https://clutch.co/"
one

2022-12-15 10:08 UTC, dhavalveera commented on src/technologies/c.json
> +    ],
done

2022-12-15 10:12 UTC, nurbek91 approved these changes

2022-12-18 22:16 UTC, merged

2022-12-18 22:16 UTC, AliasIO commented
Thanks!