OrderGroove Detection Added
wappalyzer/wappalyzer pull request #7208
Opened 2022-12-15 11:36 UTC by dhavalveera

#5956

2022-12-16 15:58 UTC, nurbek91 requested changes
Hey mate, thanks for PR. 
need some changes

2022-12-16 15:58 UTC, nurbek91 commented on src/technologies/o.json
> +    },
this can be removed lets replace with 
`"scriptSrc": "\\.ordergroove\\.com/",`

2022-12-16 15:58 UTC, nurbek91 commented on src/technologies/o.json
> +    "description": "Ordergroove's eCommerce subscription management software delivers frictionless consumer experiences for brands through promotions & retention rewards.",
` "description": "Ordergroove provides a SaaS (Software as a Service) based subscription and membership commerce platform.",`

2022-12-16 15:58 UTC, nurbek91 commented on src/technologies/o.json
> +  "OrderGroove": {
`"Ordergroove":`

2022-12-16 15:58 UTC, nurbek91 commented on src/technologies/o.json
> +    "icon": "ordergroove.png",
![Ordergroove](https://user-images.githubusercontent.com/3456008/208137528-2893f955-0ab7-464c-8394-b04385f2ce25.svg)
svg

2022-12-16 15:58 UTC, nurbek91 commented on src/technologies/o.json
> +      "recurring"
we can add "mid" also

2022-12-16 16:03 UTC, nurbek91 commented
lets replace dom with this one
```
"headers": {
      "content-security-policy": "\\.ordergroove\\.com"
    },
```

examples:
https://crest.com/en-us
https://oralb.com/
https://gillette.com/

https://www.evogennutrition.com/
https://www.missouriquiltco.com/products/creative-grids-cutting-mat-24-x-36

2022-12-17 01:16 UTC, dhavalveera commented
> lets replace dom with this one
> 
> ```
> "headers": {
>       "content-security-policy": "\\.ordergroove\\.com"
>     },
> ```
> 
> examples: https://crest.com/en-us https://oralb.com/ https://gillette.com/
> 
> https://www.evogennutrition.com/ https://www.missouriquiltco.com/products/creative-grids-cutting-mat-24-x-36

done all the improvements & modifications you referred to above.

2022-12-17 16:10 UTC, nurbek91 approved these changes

2022-12-18 22:17 UTC, merged