ReturnPrime trace added
wappalyzer/wappalyzer pull request #7213
Opened 2022-12-17 02:07 UTC by dhavalveera

**Issue #6185 **

2022-12-17 16:29 UTC, nurbek91 requested changes
Hey mate, thanks for PR

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +    "description": "Most loved and only 5 star rated RMA app to manage returns, exchanges and refunds for your shopify store.",
"description": "Return Prime is an application to manage returns for Shopify stores."

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +  "ReturnPrime": {
Return Prime

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +    ],
```
"cats": [
      100,
      102
    ],
```

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +    ],
```
"pricing": [
      "freemium",
      "low",
      "recurring"
    ],
```

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +    "scriptSrc": "//return-prime-proxy-prod\\.s3[^ ]*\\.amazonaws.com/",
`"scriptSrc": "//return-prime-proxy-prod\\.s3[^ ]*\\.amazonaws\\.com/",`

2022-12-17 16:29 UTC, nurbek91 commented on src/technologies/r.json
> +    "scriptSrc": "//return-prime-proxy-prod\\.s3[^ ]*\\.amazonaws.com/",
`"requires": "Shopify",`

2022-12-18 02:27 UTC, dhavalveera commented on src/technologies/r.json
> +    "description": "Most loved and only 5 star rated RMA app to manage returns, exchanges and refunds for your shopify store.",
done

2022-12-18 02:43 UTC, dhavalveera commented
@nurbek91 done all the improvements you stated above

2022-12-18 12:55 UTC, nurbek91 approved these changes
thanks!

2022-12-18 22:20 UTC, merged