Trace Rely BNPL
wappalyzer/wappalyzer pull request #7215
Opened 2022-12-17 03:00 UTC by dhavalveera

### Issue #6083 

https://www.picketandrail.com/products/kuka-2537-fabric-sofa-2-seater-color-c-1075?variant=16921021972550

2022-12-17 16:56 UTC, nurbek91 commented on src/technologies/p.json
> +      "/rely-shopify.min.js"
Let's add a js object instead of a script. It is less resource intensive. If in other examples the js object is not loaded and can only be detected via scriptSrc then you can leave
```
 "js": {
      "pacePay": "",
      "rely_shop_currency": "",
      "rely_month_installment": ""
    },
```

2022-12-17 17:06 UTC, nurbek91 requested changes
Hey mate, thanks. need small updates

2022-12-17 17:07 UTC, nurbek91 commented on src/technologies/p.json
> +      "/rely-shopify.min.js"
`"/rely-shopify.min.js" - > "/rely-shopify\\.min\\.js"`

2022-12-18 02:43 UTC, dhavalveera commented
@nurbek91 done all the improvements you stated above

2022-12-18 12:55 UTC, nurbek91 approved these changes
thanks!!

2022-12-18 22:20 UTC, merged