Capterra Trace added
wappalyzer/wappalyzer pull request #7216
Opened 2022-12-18 03:31 UTC by dhavalveera

### Technology Request

Capterra - Analytics

**Examples:**

https://www.regfox.com/
https://share.rothys.com/
https://www.rentmanager.com/
https://share.litter-robot.com/
https://humanity.tcpsoftware.com/

2022-12-18 13:12 UTC, nurbek91 requested changes
Hey mate, thanks for PR. need improvements

2022-12-18 13:12 UTC, nurbek91 commented on src/technologies/c.json
> +      10
Capterra is definitely not a website analytics tool. It's more of a review category.
Site analysts measure js files or some kind of embedded pixel

2022-12-18 13:12 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
"a[href*='.capterra.com/'][target='_blank'] > img[alt*='captera']", something like this should be 
Then we can tell the website is using Capterra and G2 badges.

2022-12-18 13:12 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "capterra.png",
![Capterra](https://user-images.githubusercontent.com/3456008/208300113-3001a40c-0f42-4ba1-8557-1ba93502d89d.svg)
Try to send svg icon.

2022-12-18 13:12 UTC, nurbek91 commented on src/technologies/c.json
> +    "description": "Capterra is a web analytics service that tracks and reports website traffic",
`"description": "Capterra is a technology review platform that connects sellers of B2B software to potential buyers.",

 `

2022-12-19 02:13 UTC, dhavalveera commented on src/technologies/c.json
> +      10
what other Category will be there? can you tell me that, if possible?

2022-12-19 02:16 UTC, dhavalveera commented on src/technologies/c.json
> +      10
it'll be both `10` & `90` or only `90`?

2022-12-19 02:16 UTC, dhavalveera commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
can you tell me more which trace to use or should I use both `a[href*=] img=[alt*=]`?

2022-12-19 10:56 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
If it's a badge, we should check if the badge is a link inside with an img tag
Try to find 10 or more examples and make a universal pattern for identifying a badge

2022-12-19 10:57 UTC, nurbek91 commented on src/technologies/c.json
> +      10
90 only

2022-12-19 10:59 UTC, dhavalveera commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
I didn't get you for `badge`

and should I use only `img[alt*='capterra']`? @nurbek91

2022-12-19 11:01 UTC, dhavalveera commented on src/technologies/c.json
> +      10
done

2022-12-19 11:05 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
You should use a pattern that will uniquely define only badges and not links in an article, for example, which lead to a capterra.

2022-12-19 11:08 UTC, dhavalveera commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
I checked all the examples where they've link only, not anything else @nurbek91

2022-12-20 09:22 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "a[href*='.capterra.com/'][target='_blank']",
Perhaps it will be difficult for you to understand at this stage. You can close the PR or re-read and work on it. I don't know how else to explain what is required.

2022-12-20 09:23 UTC, closed without merging