Roistat Trace Added
wappalyzer/wappalyzer pull request #7219
Opened 2022-12-18 09:24 UTC by dhavalveera

### Technology Request

**Examples:**
https://foma.ru/
https://qwintry.com/en/in
https://weblium.com/
https://progressme.ru/
https://www.pribortorg.by/en
https://xtern.ru/

2022-12-18 15:09 UTC, nurbek91 requested changes
Hey mate, thanks. need small updates

2022-12-18 15:09 UTC, nurbek91 commented on src/technologies/r.json
> +    ],
```
 "pricing": [
      "mid",
      "recurring",
      "poa"
    ],
```

2022-12-18 15:09 UTC, nurbek91 commented on src/technologies/r.json
> +    "scripts": "cloud\\.roistat\\.com",
intsead
```
 "js": {
      "roistatHost": "",
      "roistatProjectId": ""
    },
```

2022-12-19 09:43 UTC, nurbek91 approved these changes

2022-12-25 23:31 UTC, AliasIO commented
Thanks!

2022-12-25 23:31 UTC, merged