Shareaholic Trace Added
wappalyzer/wappalyzer pull request #7220
Opened 2022-12-18 10:03 UTC by dhavalveera

### Technology Request

**Examples:**

2022-12-18 15:23 UTC, nurbek91 requested changes
Hey mate, thanks for PR . Need improvements

2022-12-18 15:23 UTC, nurbek91 commented on src/technologies/s.json
> +    "icon": "shareaholic.png",
![Shareaholic](https://user-images.githubusercontent.com/3456008/208305982-267a50e2-a8af-4978-a858-e23505bb68e6.svg)
svg icons if available please

2022-12-18 15:23 UTC, nurbek91 commented on src/technologies/s.json
> +    ],
Let's remove the dom and use the js object, it's the least resource intensive
```
"js": {
      "Shareaholic": ""
    },
```

2022-12-18 15:23 UTC, nurbek91 commented on src/technologies/s.json
> +    ],
```
"pricing": [
      "freemium",
      "low",
      "recurring"
    ],
```

2022-12-18 15:23 UTC, nurbek91 commented on src/technologies/s.json
> +    "scriptSrc": "\\*/shareaholic\\.js",
this can also be removed

2022-12-18 15:23 UTC, nurbek91 commented on src/technologies/s.json
> +      10
Basically it looks like a share button, probably it needs to be added to the widget category since we don't have content marketing categories but just marketing automation
And this technology is something in between.

2022-12-18 15:24 UTC, nurbek91 commented on src/technologies/s.json
> +    "description": "Shareaholic is a comprehensive set of marketing tools to engage with your audience, get found across search and social, and grow your following",
"description": "Shareaholic is a all-in-one content amplification and monetisation platform.",

2022-12-19 02:33 UTC, dhavalveera commented on src/technologies/s.json
> +      10
I've removed `10` and replaced it with `5`

2022-12-19 09:44 UTC, nurbek91 approved these changes

2022-12-25 23:34 UTC, merged