Instamojo - Payment Processor Trace Added
wappalyzer/wappalyzer pull request #7222
Opened 2022-12-18 12:00 UTC by dhavalveera

### Technology Request

**Examples:**

https://futuregenapps.com/
https://www.fivemorselsoflove.in/
https://www.guliataxi.com/
https://7host.in/#pricing
https://docs.instamojo.com/reference/payments-api

![image](https://user-images.githubusercontent.com/32231977/208297143-0fd2e878-d1c3-459b-9136-d78c6a247574.png)

image attached for the reference, how **Instamojo** Integration happens in the Websites

2022-12-18 16:16 UTC, nurbek91 requested changes
Hey mate, thanks for PR. Need improvements

2022-12-18 16:16 UTC, nurbek91 commented on src/technologies/i.json
> +    "dom": "a[href*='instamojo\\.com'], a[rel*='im-checkout']",
` "dom": "a[href*='.instamojo\\.com/']",`

2022-12-18 16:16 UTC, nurbek91 commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/",
for checkout page https://www.instamojo.com/@futuregenapps
```
 "js": {
      "INITIAL_STATE.seller.avatar": "\\.instamojo\\.com/"
    },
```

2022-12-19 09:46 UTC, nurbek91 commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/",
or try to find examples and share, I'll see what can be done.
If there are no examples, it is better to delete

2022-12-19 09:48 UTC, nurbek91 requested changes

2022-12-19 09:48 UTC, nurbek91 commented on src/technologies/i.json
> +    "dom": "a[href*='.instamojo\\.com/'], a[rel*='im-checkout']",
a[rel*='im-checkout']" 
this part can also be removed. I don't seem to notice any traces

2022-12-19 09:48 UTC, nurbek91 commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/im\\-embed\\.min\\.js",
or try to find examples and share, I'll see what can be done.
If there are no examples, it is better to delete

2022-12-19 09:58 UTC, dhavalveera commented on src/technologies/i.json
> +    "dom": "a[href*='.instamojo\\.com/'], a[rel*='im-checkout']",
can you please review the screenshot I've shared from the Instamojo API Docs, from that I've added this trace, if you think it's not required, then I can remove it

2022-12-19 09:59 UTC, dhavalveera commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/im\\-embed\\.min\\.js",
can you please review the screenshot I've shared from the Instamojo API Docs, from that I've added this trace, if you think it's not required, then I can remove it

2022-12-19 10:20 UTC, nurbek91 commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/im\\-embed\\.min\\.js",
Yes, I looked, I need examples
the current option does not look safe and there will be many false positive results

2022-12-19 10:35 UTC, dhavalveera commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/im\\-embed\\.min\\.js",
done

2022-12-19 10:44 UTC, dhavalveera commented on src/technologies/i.json
> +    "scriptSrc": "//im\\-embed/im\\-embed\\.min\\.js",
removed the both traces which you mentioned.

2022-12-19 10:44 UTC, nurbek91 requested changes

2022-12-19 10:44 UTC, nurbek91 commented on src/technologies/i.json
> +    },
I found examples where scriptSrc is used, we can determine them by js object
https://ugcportal.com/
https://thearchitectsdiary.com/

```
"js": {
      "INITIAL_STATE.seller.avatar": "\\.instamojo\\.com/",
      "Instamojo": ""
    },
```

2022-12-19 10:46 UTC, dhavalveera commented on src/technologies/i.json
> +    },
added.

2022-12-19 10:47 UTC, nurbek91 approved these changes

2022-12-19 10:48 UTC, dhavalveera commented on src/technologies/i.json
> +    },
I checked the both examples you shared, but when I'm checking the page source, I'm not able to find the `scriptSrc` part for the trace @nurbek91

2022-12-19 10:54 UTC, nurbek91 commented on src/technologies/i.json
> +    },
> I checked the both examples you shared, but when I'm checking the page source, I'm not able to find the `scriptSrc` part for the trace @nurbek91

![image](https://user-images.githubusercontent.com/3456008/208409999-5e589daf-2566-41d3-a113-0927e5a250bf.png)

2022-12-25 23:36 UTC, merged