Bookly Trace Added
wappalyzer/wappalyzer pull request #7225
Opened 2022-12-20 03:31 UTC by dhavalveera

### Technology Request

**Examples:**

https://www.socialchefs.com/
https://rezervaceovereni.justice.cz/
https://www.spca.com/
https://spartanburghumane.org/
https://blog.scalablepress.com/
https://slim4life.com/
https://vinnietortorich.com/

2022-12-20 09:01 UTC, nurbek91 commented on src/technologies/b.json
> +    "description": "Booking and Scheduling plugin for Wordpress.",
`"description": "Bookly is a WordPress scheduling plugin that allows you to accept on-line reservations on your website and automate your booking system.",`

2022-12-20 09:07 UTC, dhavalveera commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
hey, can you please tell me, how `js` works? and from where to find these objects? @nurbek91

2022-12-20 09:16 UTC, dhavalveera commented
after replacing the `dom` & `scriptSrc` with the code snippets given/shared by you, now no websites are detecting the `Bookly` in the above-mentioned Examples @nurbek91

2022-12-20 09:17 UTC, nurbek91 commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
![image](https://user-images.githubusercontent.com/3456008/208629731-ecb9fc29-1ea8-407b-8b5c-0e32b5f60bdd.png)

2022-12-20 09:18 UTC, dhavalveera commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
but from where & how you identify those JS Objects? @nurbek91

2022-12-20 09:20 UTC, nurbek91 commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
in the console I write bookly

2022-12-20 09:21 UTC, dhavalveera commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
OK, so based on the name of the Trace or App we add, you simply write the name of it and see what all suggestions came & based on that you write `js` objects in the code? @nurbek91

2022-12-20 09:24 UTC, dhavalveera commented on src/technologies/b.json
> +    "dom": "link[href*='/plugins/bookly-responsive-appointment-booking-tool/'] link[href*='/css/bookly-main\\.css']",
I've a comment in the end of the comments section @nurbek91

2022-12-20 09:27 UTC, nurbek91 commented
> after replacing the `dom` & `scriptSrc` with the code snippets given/shared by you, now no websites are detecting the `Bookly` in the above-mentioned Examples @nurbek91
This should work. Take your time, look what's wrong

2022-12-20 09:33 UTC, dhavalveera commented
> > after replacing the `dom` & `scriptSrc` with the code snippets given/shared by you, now no websites are detecting the `Bookly` in the above-mentioned Examples @nurbek91
> 
> This should work. Take your time, look what's wrong

done, except 1 site, it's working, the reason being that in that 1 site, the way the script is loaded is quite different compared to our trace

2022-12-20 09:35 UTC, nurbek91 commented
> > > after replacing the `dom` & `scriptSrc` with the code snippets given/shared by you, now no websites are detecting the `Bookly` in the above-mentioned Examples @nurbek91
> > 
> > 
> > This should work. Take your time, look what's wrong
> 
> done, except 1 site, it's working, the reason being that in that 1 site, the way the script is loaded is quite different compared to our trace

You need to figure out why. Suddenly there are a lot of such sites and we will not get the full result
Also right now we don't cover the pro version
When you tested, did you check if the plugin version is taken

2022-12-20 09:39 UTC, dhavalveera commented
> > > > after replacing the `dom` & `scriptSrc` with the code snippets given/shared by you, now no websites are detecting the `Bookly` in the above-mentioned Examples @nurbek91
> > > 
> > > 
> > > This should work. Take your time, look what's wrong
> > 
> > 
> > done, except 1 site, it's working, the reason being that in that 1 site, the way the script is loaded is quite different compared to our trace
> 
> You need to figure out why. Suddenly there are a lot of such sites and we will not get the full result Also right now we don't cover the pro version When you tested, did you check if the plugin version is taken

the reason being is we're making a trace on `/plugins/bookly-responsive-appointment-booking-tool/.+\\.js(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1` this way, but that 1 website which I'm referring they've something like this `[/plugins/appointment-booking/frontend/resources/js/bookly.js?ver=15.2](view-source:https://spartanburghumane.org/wp-content/plugins/appointment-booking/frontend/resources/js/bookly.js?ver=15.2)`, so the trace got different due to which it's not identifying the Plugin

2022-12-20 10:51 UTC, dhavalveera commented
@nurbek91 - I tried to change the regex you tried but for 1 or 2 I think it's not working, and not able to identify any other way for that... and also for that pro I didn't find any trace.

2022-12-20 16:18 UTC, nurbek91 requested changes

2022-12-20 16:18 UTC, nurbek91 commented on src/technologies/b.json
> +    },
```

  "js": {
      "bookly": "",
      "booklyCustomerProfile": "",
      "BooklyL10n.daysShort": ""
    },
```

2022-12-20 16:18 UTC, nurbek91 commented on src/technologies/b.json
> +    "scriptSrc": "/.+\\/bookly/.\\*.js(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1",
try to use this one 
`"scriptSrc": "/wp-content/plugins/bookly-responsive-appointment-booking-tool/.+\\.js(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1",`

because https://wordpress.org/plugins/bookly-responsive-appointment-booking-tool/  official plugin name for https://www.booking-wp-plugin.com

2022-12-20 16:22 UTC, nurbek91 commented
> @nurbek91 - I tried to change the regex you tried but for 1 or 2 I think it's not working, and not able to identify any other way for that... and also for that pro I didn't find any trace.

This will work since there are js objects
If it is not detected locally, try increasing the time for analyzing downloaded files
path:
src/npm/drivers.js

line 730
await sleep(1000) -> await sleep(5000)

2022-12-20 16:40 UTC, nurbek91 commented
_he reason being is we're making a trace on /plugins/bookly-responsive-appointment-booking-tool/.+\\.js(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1 this way, but that 1 website which I'm referring they've something like this [/plugins/appointment-booking/frontend/resources/js/bookly.js?ver=15.2](view-source:https://spartanburghumane.org/wp-content/plugins/appointment-booking/frontend/resources/js/bookly.js?ver=15.2), so the trace got different due to which it's not identifying the Plugin_

Is this an old version of bookly or another plugin?
https://spartanburghumane.org/wp-content/plugins/appointment-booking/frontend/resources/js/bookly.js?ver=15.2

By this name, I did not find the plugin on the official WordPress page
https://wordpress.org/plugins/search/appointment-booking/  

if the old version you can change the regex a bit so that both options are taken. The main thing for us is to take the version through scriptSrc, we have js and we don’t really need to check just scriptSrc

2022-12-21 01:58 UTC, dhavalveera commented
> > @nurbek91 - I tried to change the regex you tried but for 1 or 2 I think it's not working, and not able to identify any other way for that... and also for that pro I didn't find any trace.
> 
> This will work since there are js objects If it is not detected locally, try increasing the time for analyzing downloaded files path: src/npm/drivers.js
> 
> line 730 await sleep(1000) -> await sleep(5000)

but this isn't for npm package, and we're running on webextension

2022-12-21 15:21 UTC, nurbek91 approved these changes

2022-12-25 23:36 UTC, merged