Webpushr Trace added
wappalyzer/wappalyzer pull request #7227
Opened 2022-12-20 08:51 UTC by dhavalveera

### Technology Request

**Examples:**

https://radioink.com/
https://www.healthy-holistic-living.com/
https://www.heartlandvetsupply.com/
https://radiofacts.com/
https://unrealfacts.com/
http://www.dailycameranews.com/
https://www.desiblitz.com/

2022-12-20 16:30 UTC, nurbek91 requested changes
Hey mate, thanks for PR. Need improvements

2022-12-20 16:30 UTC, nurbek91 commented on src/technologies/w.json
> +    "website": "https://www.webpushr.com"
```
"pricing": [
      "recurring",
      "freemium",
      "low"
    ],
```

2022-12-20 16:30 UTC, nurbek91 commented on src/technologies/w.json
> +    "description": "Webpushr is the new standard for Web Push Notifications.",
Less promotional description with structure like 
Webpushr is .........................

2022-12-20 16:30 UTC, nurbek91 commented on src/technologies/w.json
> +    },
"js": {
      "WebPushr.notificationCard": "",
      "webpushr_display_button": ""
    },

2022-12-20 16:30 UTC, nurbek91 commented on src/technologies/w.json
> +    "scripts": "cdn\\.webpushr\\.com/app\\.min\\.js",
You can delete or leave if there are examples without js objects and this code will work

2022-12-21 15:29 UTC, nurbek91 requested changes

2022-12-21 15:29 UTC, nurbek91 commented on src/technologies/w.json
> +    "description": "Webpushr is Push Notification which supports both Mobile & Desktop devices.",
`"description": "Webpushr is a web push notification platform that supports mobile and desktop devices."
`

2022-12-21 15:29 UTC, nurbek91 commented on src/technologies/w.json
> +      "webpushr": "",
can be deleted
`"webpushr": "",  `
If it is possible to check like this, then it is better to add it in this way to allow us to minimize random triggers
`"WebPushr.notificationCard": "",`

2022-12-21 15:29 UTC, nurbek91 commented on src/technologies/w.json
> +    "scripts": "cdn\\.webpushr\\.com/app\\.min\\.js",
This line can be deleted If we want to leave a link where there are no js objects, this line will help us identify the technology

2022-12-22 02:14 UTC, dhavalveera commented on src/technologies/w.json
> +    "scripts": "cdn\\.webpushr\\.com/app\\.min\\.js",
I think we can put this as well, where there are no js objects and mostly this line will help us to identify the technology.

2022-12-23 14:08 UTC, nurbek91 approved these changes

2022-12-25 23:37 UTC, merged