CanvasJs Trace Added
wappalyzer/wappalyzer pull request #7239
Opened 2022-12-23 03:10 UTC by dhavalveera

### Technology Request

**Examples:**

**using `script`:**
https://wow-petguide.com/

**using `js`:**
https://www.globalpropertyguide.com/
https://app.guardian.periscopedata.com/login?controller=welcome
https://fcx.com/
https://orientation.georgian.edu/
https://www.policyed.org/

2022-12-24 05:27 UTC, nurbek91 requested changes
Hey mate, thanks for PR. Need improvements

2022-12-24 05:27 UTC, nurbek91 commented on src/technologies/c.json
> +  "CanvasJs": {
CanvasJS

2022-12-24 05:27 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "canvasjs.png",
![CanvasJS](https://user-images.githubusercontent.com/3456008/209422658-5d49a0a1-349f-479e-9683-8022a2c0148b.svg) svg

2022-12-24 05:27 UTC, nurbek91 commented on src/technologies/c.json
> +    "scriptSrc": "/.+\\.canvasjs/.+\\.js(?:\\?v=(\\d+(?:\\.\\d+)+))?\\;version:\\1",
How will this code work in such cases?
http://www.tazabek.kg/
/ui-js/admingraph/canvasjs-1.4.1/canvasjs.min.js

https://www.wow-petguide.com/js/jquery.canvasjs.min.js?v=1.52
https://www.architectsjournal.co.uk/wp-content/plugins/aj100/js/jquery.canvasjs.min.js?ver=1.3

CanvasJS.Chart.version return Chart version btw

2022-12-25 04:21 UTC, nurbek91 requested changes
according previous request

2022-12-25 04:27 UTC, dhavalveera commented
> according previous request

now directly checking the `/canvasjs.min` part

2022-12-25 04:34 UTC, nurbek91 commented
![image](https://user-images.githubusercontent.com/3456008/209457030-0508b0f6-991e-49c8-9c26-22426c51859c.png)

2022-12-25 04:42 UTC, nurbek91 commented
Open PR back please. I'll post in the comments later today how to fix it

2022-12-25 05:07 UTC, nurbek91 commented
```
 "CanvasJS": {
    "cats": [
      25
    ],
    "description": "CanvasJS charts is a data visualisation library that runs across multiple devices and browsers.",
    "js": {
      "CanvasJS.Chart": "",
      "CanvasJS.Chart.version": "^v(.+)$\\;version:\\1"
    },
    "website": "https://canvasjs.com"
```

2022-12-25 05:21 UTC, nurbek91 commented on src/technologies/c.json
> +    "scriptSrc": "/canvasjs/.+\\.js(?:\\?v=(\\d+(?:\\.\\d+)+))?\\;version:\\1",
delete this one

2022-12-25 05:30 UTC, nurbek91 approved these changes

2022-12-25 23:41 UTC, merged