Teamtailor Trace Added
wappalyzer/wappalyzer pull request #7249
Opened 2022-12-25 12:08 UTC by dhavalveera

### Technology Request

**Examples:**

https://jobs.amphi.com/
https://careers.airhelp.com/
https://careers.arsenal.com/
https://careers.mpb.com/
https://careers.assessment.aon.com/
https://careers.ro.mdpi.com/

2022-12-25 12:24 UTC, nurbek91 requested changes

2022-12-25 12:24 UTC, nurbek91 commented on src/technologies/t.json
> +    "icon": "teamtailor.png",
![Teamtailor](https://user-images.githubusercontent.com/3456008/209467640-3cea64fa-6e80-4975-a4f7-72bab5a974c3.svg)
svg available

2022-12-25 12:24 UTC, nurbek91 commented on src/technologies/t.json
> +    "description": "Teamtailor is Recruitment & Marketing Platform and its used to manage and hire top talent.",
Teamtailor is an applicant tracking system, career site and analytics dashboard combined, mobile friendly, all-in-one recruitment platform.

2022-12-25 12:24 UTC, nurbek91 commented on src/technologies/t.json
> +    ],
```
"pricing": [
      "mid",
      "recurring"
    ],
```

2022-12-26 01:52 UTC, dhavalveera commented on src/technologies/t.json
> +    "icon": "teamtailor.png",
can you please tell me from where you get all this svg icons?

2022-12-26 02:10 UTC, dhavalveera commented
@nurbek91 @AliasIO = can you please help me here why the validate check is failing? till yesterday everything was working fine

2022-12-26 02:53 UTC, merged

2022-12-26 02:54 UTC, AliasIO commented
Looks like a accidentally pasted some text in the wrong place, nothing to do with your changes.  👍

2022-12-26 03:22 UTC, dhavalveera commented
> Looks like a accidentally pasted some text in the wrong place, nothing to do with your changes. 👍

OK! Great