Conviva Trace Added
wappalyzer/wappalyzer pull request #7269
Opened 2022-12-31 10:48 UTC by dhavalveera

### Technology Request

**Examples:**

https://tv.yousee.dk/login
https://www.sonyliv.com/
https://www.factoriadeficcion.com/
https://www.xploretv.at/login
https://xploretv.si/setup?step=language
https://www.yasss.es/

2023-01-02 16:41 UTC, nurbek91 requested changes

2023-01-02 16:41 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "conviva.png",
![Conviva](https://user-images.githubusercontent.com/3456008/210258382-ba6eaf0f-09be-428f-8ff4-356393364b32.svg)
svg available mate

2023-01-02 16:41 UTC, nurbek91 commented on src/technologies/c.json
> +    "description": "Conviva is a streaming partner & a single source of truth of streaming analytics for your entire team.",
Conviva is a census, continuous measurement and engagement platform for streaming media.

2023-01-02 16:41 UTC, nurbek91 commented on src/technologies/c.json
> +      14
103
14

2023-01-02 16:41 UTC, nurbek91 commented on src/technologies/c.json
> +      "Conviva.Client.version": "^([0-9.]+)?\\;version:\\1"
`"Conviva.Client.version": "^([0-9\\.]+)$\\;version:\\1"`

2023-01-03 01:55 UTC, dhavalveera commented on src/technologies/c.json
> +    "icon": "conviva.png",
from where you get the `SVG`s?

2023-01-04 09:41 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "conviva.png",
from website

2023-01-04 09:42 UTC, nurbek91 approved these changes

2023-01-15 20:45 UTC, merged