ElementsKit - Elementor AddOn Trace Added
wappalyzer/wappalyzer pull request #7271
Opened 2023-01-01 10:16 UTC by dhavalveera

### Technology Request

**Examples:**

https://www.bertuccis.com/
https://esg.outlookindia.com/
https://laser.newhaven.edu/
https://cpm.org/
https://www.1800dentist.com/
https://www.turbotenant.com/

2023-01-02 16:51 UTC, nurbek91 requested changes

2023-01-02 16:51 UTC, nurbek91 commented on src/technologies/e.json
> +    "icon": "elementskit.png",
![ElementsKit](https://user-images.githubusercontent.com/3456008/210259185-8cd0d072-9dbe-4868-bc62-8718c435099f.svg)
svg available u can take it from website source usually

2023-01-02 16:51 UTC, nurbek91 commented on src/technologies/e.json
> +    "description": "ElementsKit is an ultimate and all-in-one addons for Elementor Page Builder.",
ElementsKit is an addon for Elementor that adds additional customisation options to the page builder.

2023-01-02 16:51 UTC, nurbek91 commented on src/technologies/e.json
> +      51,
51 can be removed if its Elementor plugin

2023-01-02 16:51 UTC, nurbek91 commented on src/technologies/e.json
> +    ],
can u share with pricing if available i am not sure that plugin can has high pricing 
btw we can specify only one variant from three low, high, mid because i think  its for UI element  config which understand and has only three display view

2023-01-03 01:59 UTC, dhavalveera commented on src/technologies/e.json
> +    "icon": "elementskit.png",
I tried to get from the source code of the website only, but didn't get, and the one I was getting was with the name like `Logo + ElementsKit` it was this way

2023-01-03 02:12 UTC, dhavalveera commented on src/technologies/e.json
> +    ],
https://wpmet.com/plugin/elementskit/pricing/

2023-01-04 09:44 UTC, nurbek91 approved these changes

2023-01-15 20:45 UTC, merged