Master Slider Trace Added'
wappalyzer/wappalyzer pull request #7272
Opened 2023-01-01 10:52 UTC by dhavalveera

### Technology Request

**Examples:**

https://www.partzilla.com/
https://websites.gotsport.com/clubsite/?p=11521
https://www.popularwoodworking.com/
https://fashionshow.fitnyc.edu/
https://pga.pixelfederation.com/
https://prayingmedic.com/

2023-01-02 17:17 UTC, nurbek91 requested changes

2023-01-02 17:17 UTC, nurbek91 commented on src/technologies/m.json
> +    "dom": "body._masterslider, link[href*='/masterslider\\.(?:main.css|css)(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1']",
Hey mate did you test this code did you manage to get the versions?
link[href*='/masterslider\\.(?:main.css|css)(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1']

2023-01-02 17:17 UTC, nurbek91 commented on src/technologies/m.json
> +      "MasterSlider": ""
MasterSlider.version we can take version in this way which less resource intensive

2023-01-02 17:17 UTC, nurbek91 commented on src/technologies/m.json
> +    "description": "Master Slider is a stunning, super smooth, responsive, and touch friendly slider",
Master Slider is an SEO friendly, responsive image and video slider.

2023-01-02 17:17 UTC, nurbek91 commented on src/technologies/m.json
> +      59
![image](https://user-images.githubusercontent.com/3456008/210261947-8a0ca78c-ed16-4435-a834-0116dbd16f40.png)
This should fall under the WordPress Plugin category.
You can still add it as two different technologies
Master Slider 59 js lib
Master Slider plugin 87 wp plugins
You just need to understand the examples and learn to distinguish them.
Depends on how popular the technology is before adding them separately

2023-01-03 02:20 UTC, dhavalveera commented on src/technologies/m.json
> +      59
the reason being for adding it in category 59 was like, from the above examples, few examples are using WP & some aren't using WP at all

2023-01-04 10:02 UTC, nurbek91 commented on src/technologies/m.json
> +    "dom": "body._masterslider, link[href*='/masterslider\\.(?:main.css|css)(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1']",
```
"Master Slider": {
    "cats": [
      7
    ],
    "description": "Master Slider is an SEO friendly, responsive image and video slider.",
    "icon": "master_slider.png",
    "js": {
      "MasterSlider": "",
      "MasterSlider.version": "^([0-9\\.]+)$\\;version:\\1"
    },
    "website": "https://www.masterslider.com"
  },

  "Master Slider Plugin": {
    "cats": [
      87
    ],
    "description": "Master Slider is an SEO friendly, responsive image and video slider plugin for WordPress.",
    "icon": "master_slider.png",
    "requires": "WordPress",
    "implies": "Master Slider",
    "dom": {
      "link#ms-main-css": {
        "attributes": {
          "href": "/wp-content/plugins/masterslider/.+\\.css(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1"
        }
      }
    },
    "website": "https://wordpress.org/plugins/master-slider"
  },
```

2023-01-04 10:05 UTC, nurbek91 commented on src/technologies/m.json
> +    "dom": "body._masterslider, link[href*='/masterslider.(?:main.css|css)(?:?ver=(d+(?:.d+)+))?;version:\\1']",
Hey mate dom will not work in this way should be like this
```
   "dom": {
      "link#ms-main-css": {
        "attributes": {
          "href": "/wp-content/plugins/masterslider/.+\\.css(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1"
        }
      }
    },
```

2023-01-04 10:07 UTC, nurbek91 commented on src/technologies/m.json
> +      59
We cannot combine plugin versions and standalone version into one pile.
Of course, we can do it this way, but it will probably be a bit incorrect.
Ideally, this is how it should be.
```
"Master Slider": {
    "cats": [
      7
    ],
    "description": "Master Slider is an SEO friendly, responsive image and video slider.",
    "icon": "master_slider.png",
    "js": {
      "MasterSlider": "",
      "MasterSlider.version": "^([0-9\\.]+)$\\;version:\\1"
    },
    "website": "https://www.masterslider.com"
  },

  "Master Slider Plugin": {
    "cats": [
      87
    ],
    "description": "Master Slider is an SEO friendly, responsive image and video slider plugin for WordPress.",
    "icon": "master_slider.png",
    "requires": "WordPress",
    "implies": "Master Slider",
    "dom": {
      "link#ms-main-css": {
        "attributes": {
          "href": "/wp-content/plugins/masterslider/.+\\.css(?:\\?ver=(\\d+(?:\\.\\d+)+))?\\;version:\\1"
        }
      }
    },
    "website": "https://wordpress.org/plugins/master-slider"
  },
```

2023-01-15 20:45 UTC, merged