JetElements - Elementor AddOn Trace Added
wappalyzer/wappalyzer pull request #7273
Opened 2023-01-01 11:07 UTC by dhavalveera

### Technology Request

**Examples:**

https://signalscv.com/
https://blog.stuller.com/
https://www.signpost.com/
https://advertise.jerseydigs.com/
https://www.icontact.com/
https://www.securenetsystems.net/

2023-01-04 17:52 UTC, nurbek91 requested changes

2023-01-04 17:52 UTC, nurbek91 commented on src/technologies/j.json
> +    ],
![image](https://user-images.githubusercontent.com/3456008/210617231-999e16d9-f31b-42a7-80d5-09a4d7b1cac9.png)
![image](https://user-images.githubusercontent.com/3456008/210617284-cfe24f31-2b96-4337-9e71-24c1aa1c5742.png)

2023-01-04 17:52 UTC, nurbek91 commented on src/technologies/j.json
> +  "JetElements": {
Crocoblock JetElements

2023-01-04 17:52 UTC, nurbek91 commented on src/technologies/j.json
> +    "icon": "jet_elements.png",
![Crocoblock](https://user-images.githubusercontent.com/3456008/210618308-3a8879b6-90dc-49df-8060-8c78cbb88d5f.svg)
svg available

2023-01-05 15:10 UTC, nurbek91 requested changes

2023-01-05 15:10 UTC, nurbek91 commented on package.json
> +    "prettify": "jsonlint -si --trim-trailing-commas --enforce-double-quotes ./src/categories.json ./src/technologies/m.json",
is this update needed?

2023-01-06 01:56 UTC, dhavalveera commented on package.json
> +    "prettify": "jsonlint -si --trim-trailing-commas --enforce-double-quotes ./src/categories.json ./src/technologies/m.json",
this isn't required, actually in my windows when I run `yarn run prettify` that time this => `"prettify": "jsonlint -si --trim-trailing-commas --enforce-double-quotes ./src/categories.json ./src/technologies/*.json"` command isn't working for me, it's saying no files found so for that I've pass the file name to prettify it

2023-01-06 13:17 UTC, nurbek91 approved these changes

2023-01-15 20:45 UTC, merged