Add detection for WordPress themes Twenty Twenty-Two and Twenty Twenty-Three
wappalyzer/wappalyzer pull request #7286
Opened 2023-01-04 01:38 UTC by felixarntz

This PR intends to add detection for the WordPress default themes Twenty Twenty-Two and Twenty Twenty-Three, which are currently missing from the list of WordPress default themes that Wappalyzer detects.

Before reviewing the code, please read the following concerns:
* Those two themes (as well as likely any WordPress default themes in the future) follow a new theme development paradigm which, while it has several benefits, makes it quite a bit harder to identify such a theme being used.
* Twenty Twenty-Two still comes with a stylesheet that identifies the theme, so this one is still relatively straightforward, however it already lacks all other criteria that Wappalyzer relies on to detect previous WordPress default themes. Twenty Twenty-Three however does not load any stylesheet that identifies the theme, so here the PR is currently not working.
* The only thing that both themes _do_ load which we may be able to detect is some web font files that are within the theme's directory (`wp-content/themes/twentytwentytwo/assets/fonts` and `wp-content/themes/twentytwentythree/assets/fonts` respectively). However I'm unsure whether/how we can detect that via Wappalyzer.
    * I haven't found any technology property related to web fonts. Potentially we can somehow use the `css` property to detect the web font references? That's what I tried, but I don't know how that property is supposed to work, so any advice would be much appreciated.
    * FYI in both of the themes the web font reference is within inline CSS (i.e. not in an external CSS file). Maybe that helps.

2023-01-04 01:39 UTC, felixarntz commented
@AliasIO Do you have any advice on the issue I outline above? Is there a way for Wappalyzer to inspect web fonts loaded by a page, or web fonts referenced in CSS?

2023-01-04 01:40 UTC, felixarntz commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentythree\\/assets\\/fonts\\/",
As outlined in the PR description, this is not working (making the Twenty Twenty-Three detection fail, since that's the only thing that can identify it).

2023-01-04 01:40 UTC, felixarntz commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentytwo\\/assets\\/fonts\\/",
As outlined in the PR description, this is not working.

2023-01-04 09:01 UTC, nurbek91 commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentythree\\/assets\\/fonts\\/",
examples
https://opposition24.com/
http://wp-themes.com/
http://playr.org/
https://wp-a2z.org/
https://techkyuniverse.com/

2023-01-04 09:35 UTC, nurbek91 requested changes
Hey mate thanks for PR!!

2023-01-04 09:35 UTC, nurbek91 commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentythree\\/assets\\/fonts\\/",
Hey mate yes confirm. but i couldn't detect when test it locally 

```
"dom": {
      "style#wp-webfonts-inline-css": {
          "text": "/wp-content/themes/twentytwentythree/assets/fonts/"
      }
    }, 
```
this code help me and its less resource intensive because we specify style ID

2023-01-04 09:35 UTC, nurbek91 commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentytwo\\/assets\\/fonts\\/",
examples:
https://apkxmod.org/
https://impactwrestling.com/
http://mazochina.com/
http://seiichiegawa.jp/
https://stanceworks.com/
https://sola.ai/

```
"dom": {
      "style#wp-webfonts-inline-css": {
          "text": "/wp-content/themes/twentytwentytwo/assets/fonts/"
      }
    }, 
```

2023-01-04 09:38 UTC, nurbek91 commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentytwo\\/assets\\/fonts\\/",
"dom": {
      "style#wp-webfonts-inline-css": {
          "text": "/wp-content/themes/twentytwentytwo/assets/fonts/"
      }
    },

2023-01-04 09:39 UTC, nurbek91 commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentythree\\/assets\\/fonts\\/",
```
"dom": {
      "style#wp-webfonts-inline-css": {
          "text": "/wp-content/themes/twentytwentythree/assets/fonts/"
      }
    }, 
```

2023-01-04 20:56 UTC, felixarntz commented
@nurbek91 @AliasIO Thank you for the guidance! I've updated the PR with the `dom` approach, works like a charm now!

2023-01-04 21:00 UTC, felixarntz commented on src/technologies/t.json
> +    "css": "\\/wp-content\\/themes\\/twentytwentythree\\/assets\\/fonts\\/",
@nurbek91 After further review, it looks like depending on the version of WordPress core (not the theme itself), the ID here can be either `wp-webfonts-inline-css` or just `webfonts-inline-css`. So I've updated the PR to cater for both.

2023-01-15 20:47 UTC, merged

2023-01-15 20:48 UTC, AliasIO commented
Cheers!