Noibu Error Tracking Trace Added
wappalyzer/wappalyzer pull request #7320
Opened 2023-01-13 12:34 UTC by dhavalveera

### Technology Request

**`Examples:`**

https://www.sharperimage.com/
https://www.onehanesplace.com/brands/just-my-size.html
https://iheartcats.com/
https://www.signaturehardware.com/
https://www.silhouettedesignstore.com/

2023-01-14 08:34 UTC, nurbek91 requested changes

2023-01-14 08:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "icon": "noibu.png",
![Noibu](https://user-images.githubusercontent.com/3456008/212463489-fbf38dd2-5cf5-4d74-85d6-fe89ea7c37d1.svg)
svg available

2023-01-14 08:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "description": "Noibu is used to deliver better digital experience by preventing lost of revenue. Detect, prioritize & resolve critical eCommerce errors.",
Noibu helps ecommerce websites detect revenue-impacting errors on their websites and provides them with the information needed to resolve them.

2023-01-14 08:34 UTC, nurbek91 commented on src/technologies/n.json
> +    "icon": "noibu.png",
```
"pricing": [
      "poa"
    ],
"saas": true,
```

2023-01-14 08:34 UTC, nurbek91 commented on src/technologies/n.json
> +      "NOIBUJS_CONFIG": ""
NOIBUJS_CONFIG.scriptID Isn't that the version by any chance? I'm not sure

2023-01-15 02:16 UTC, dhavalveera commented on src/technologies/n.json
> +      "NOIBUJS_CONFIG": ""
nope, it's not a version, because everyone have the scriptID, any I don't think that it'll be a version

2023-01-15 02:21 UTC, nurbek91 approved these changes

2023-01-15 20:42 UTC, merged