Truepush Detection added
wappalyzer/wappalyzer pull request #7359
Opened 2023-01-20 12:43 UTC by dhavalveera

### Technology Request

**`Examples:`**

https://footballtoolbox.net/
https://www.floodmap.net/
https://www.papillesetpupilles.fr/

2023-01-21 17:44 UTC, nurbek91 requested changes

2023-01-21 17:44 UTC, nurbek91 commented on src/technologies/t.json
> +    "description": "Truepush is web-based push notification service available for PWA, AMP, WordPress, and Shopify",
`"description": "Truepush is web-based push notification service available for PWA, AMP, WordPress, and Shopify.",`

2023-01-21 17:44 UTC, nurbek91 commented on src/technologies/t.json
> +    "icon": "truepush.svg",
![TruePush](https://user-images.githubusercontent.com/3456008/213879717-44d1fe9f-f483-4126-82db-8cf44e06c318.svg)
centered

2023-01-21 17:44 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
This will not work because also we can take version from js var
We ca delete scriptSrc

2023-01-21 17:44 UTC, nurbek91 commented on src/technologies/t.json
> +    },
```
"js": {
      "truepush": "",
      "truepushVersionInfo.key": "v([\\d\\.]+)\\;version:\\1"
    },
```

2023-01-21 17:44 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
Truepush i guess also open-source

2023-01-22 02:32 UTC, dhavalveera commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
no, Truepush isn't a OSS

2023-01-22 16:47 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
This part should be removed anyway, the code is not working as I wrote earlier

2023-01-22 18:35 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
https://affiliatedigitalmarketings.quora.com/Truepush-Totally-Free-Web-Push-Notifications-is-open-source-software?ch=1&share=7cab9667

2023-01-22 18:36 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
https://affiliatedigitalmarketings.quora.com/Truepush-Totally-Free-Web-Push-Notifications-is-open-source-software?ch=1&share=7cab9667

2023-01-23 01:48 UTC, dhavalveera commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
Sorry, I've noticed it but forgotten to remove

2023-01-23 01:52 UTC, dhavalveera commented on src/technologies/t.json
> +    "scriptSrc": "\\.truepush\\.com/sdk/([\\d\\.]+)\\;version:\\1",
but on the website of Truepush - there's no GitHub repo link is provided as well as there's nothing written as Open Source on their website.

also if you search Truepush on google as well, you won't get GitHub repo link

2023-01-23 12:08 UTC, nurbek91 approved these changes

2023-01-26 21:33 UTC, merged