Add ISAY / cms
wappalyzer/wappalyzer pull request #7391
Opened 2023-01-30 10:11 UTC by agmmnn

**ISAY**(Centralized Content Management for Websites) is a CMS service provided by the Turkish Ministry of Interior for governorships, district governorships and various official websites.

### website:
https://www.icisleri.gov.tr/internet-sayfalari-yonetimi-isay

### examples:
http://istanbul.gov.tr/
http://ankara.gov.tr/
https://afad.gov.tr/
http://alanya.gov.tr/

2023-01-31 11:47 UTC, dhavalveera commented on src/technologies/i.json
> +    "html": "<div class=\"topbar-img\"><img class=\"img-fluid\" src=\"/Areas/WebPart/Contents/FHeader/img/ataturk.svg\"></div>",
instead of `"html"` you can use:

```json
"dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
```

2023-01-31 11:47 UTC, dhavalveera requested changes
instead of `"html"` you can use:

```json
"dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
```

2023-01-31 11:49 UTC, dhavalveera requested changes

2023-01-31 11:49 UTC, dhavalveera commented on src/technologies/i.json
> +    "html": "<div class=\"topbar-img\"><img class=\"img-fluid\" src=\"/Areas/WebPart/Contents/FHeader/img/ataturk.svg\"></div>",
instead of `"html"` you can use:

```json
"dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
```

2023-01-31 14:21 UTC, agmmnn commented on src/technologies/i.json
> +    "html": "<div class=\"topbar-img\"><img class=\"img-fluid\" src=\"/Areas/WebPart/Contents/FHeader/img/ataturk.svg\"></div>",
> instead of `"html"` you can use:
> 
> ```json
> "dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
> ```

Thanks, I changed it. https://github.com/wappalyzer/wappalyzer/pull/7391/commits/815e5b749f2b301d455dc109ae52046c325213e2

2023-01-31 20:33 UTC, nurbek91 commented on src/technologies/i.json
> +    "dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
**_div.topbar-img_** 
I tried to find false-positive results, but everything seems to be fine and all links are located in the domain zone Turkey.
I think the requires line should help cut off random results
![image](https://user-images.githubusercontent.com/3456008/215875980-c3506fdd-d340-4bc1-97f8-955f46d0f082.png)

2023-01-31 22:25 UTC, agmmnn commented on src/technologies/i.json
> +    "dom": "div.topbar-img, img[src*='/Areas/WebPart/Contents/FHeader/img/ataturk.svg']",
I also realized that asp.net infrastructure was used, but I did not know the "requires" rule. Thanks for contribution: https://github.com/wappalyzer/wappalyzer/pull/7391/commits/3580b3af11f023a523c834515d3c96790df03a0c 

And yes, all sites are located in the Turkey domain zone, I don't think there will be any exceptions cause they're all part of government agencies.

2023-02-27 00:24 UTC, merged

2023-02-27 00:24 UTC, AliasIO commented
Thanks!