Add Phoenix Framework, Phoenix LiveView and Elixir detection
wappalyzer/wappalyzer pull request #7452
Opened 2023-02-17 18:32 UTC by osbre

Websites for test:
- https://livebeats.fly.dev/signin
- https://fly.io/app/sign-in

2023-02-20 03:21 UTC, nurbek91 requested changes
Hey mate, thanks!!
examples:
https://www.polimeter.org/en
https://clubsantos.mx/
https://www.cars.com/

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/p.json
> +    "dom": "[data-phx-session]",
It may be possible to specify some specific tag, in the examples I saw the div tag is used everywhere
![image](https://user-images.githubusercontent.com/3456008/220001032-2c86627b-aa0d-4091-ae20-031d1adf6b1b.png)

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/p.json
> +    "description": "Phoenix is a productive web framework that does not compromise speed and maintainability.",
"description": "Phoenix Framework is an open-source web application framework built using the Elixir programming language.",

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/p.json
> +    "description": "Phoenix is a productive web framework that does not compromise speed and maintainability.",
"oss": true,

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/e.json
> +    "icon": "Elixir.png",
![Elixir](https://user-images.githubusercontent.com/3456008/220001976-da0955f5-195a-4c5d-a023-0ca0409a2c55.svg)
svg 32x32

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/p.json
> +    "icon": "Phoenix Framework.png",
![Phoenix Framework](https://user-images.githubusercontent.com/3456008/220002015-e66cf3e5-46b0-40be-9171-6d4c4556b74a.svg)
32x32 svg

2023-02-20 03:21 UTC, nurbek91 commented on src/technologies/p.json
> +    },
Not sure about this, may need to be removed

2023-02-20 09:29 UTC, osbre commented on src/technologies/p.json
> +    },
This part has very high chances to be present on the websites built withPhoenix LiveView, because
[it comes in every project by default](https://github.com/phoenixframework/phoenix/blob/bf06ab9c911e3f5fc0cc98e2a228fad1fe4e8eb2/installer/templates/phx_assets/app.js#L40). Would it improve the performance compared to the DOM-based search?

2023-02-20 09:59 UTC, osbre commented
@nurbek91 The SVG files you've suggested as a replacement have file sizes 6x and 8x times more than SVG originals, which, in my opinion, ruins the purpose of the SVG file format if being converted from PNG originals. Is there a specific reason SVG has to be used here?

2023-02-20 16:53 UTC, nurbek91 commented
> @nurbek91 The SVG files you've suggested as a replacement have bigger file sizes than PNG originals, which, in my opinion, ruins the purpose of the SVG file format if being converted from PNG originals. Is there a specific reason SVG has to be used here?

If there is such an opportunity to take svg, then it is always a priority. Probably quality related. If you can compress svg it will be cool

2023-02-20 16:56 UTC, nurbek91 reviewed
need to update icons, about js part I'll leave it up to Elbert.my knowledge is not enough in this matter and I always try to avoid false positive results

```
"js": {
      "liveSocket.socket": ""
    },
```

2023-02-25 02:14 UTC, nurbek91 approved these changes

2023-02-27 00:37 UTC, merged

2023-02-27 00:37 UTC, AliasIO commented
Looks good to me, thanks!