Apexchart detection added
wappalyzer/wappalyzer pull request #7476
Opened 2023-03-01 01:44 UTC by dhavalveera

2023-03-01 20:11 UTC, nurbek91 requested changes
examples:
https://www.tigatravel.com/
https://www.myarena.ru/
https://bitcambio.com.br/
https://www.ms.gov/

2023-03-01 20:11 UTC, nurbek91 commented on src/technologies/a.json
> +    "dom": "div.apexcharts-canvas",
let's delete this

2023-03-01 20:11 UTC, nurbek91 commented on src/technologies/a.json
> +      "Apex": "",
let's delete this

2023-03-01 20:11 UTC, nurbek91 commented on src/technologies/a.json
> +      "ApexCharts": ""
i think it will be enough

2023-03-01 20:11 UTC, nurbek91 commented on src/technologies/a.json
> +    "description": "ApexCharts is a modern JavaScript charting library that empowers developers to build interactive data visualizations for commercial and non-commercial projects",
"ApexCharts is a modern JavaScript charting library that empowers developers to build interactive data visualisations for commercial and non-commercial projects."

2023-03-02 01:27 UTC, dhavalveera commented on src/technologies/a.json
> +      "ApexCharts": ""
Do I've to delete the `dom` & `Apex` in JS or what?

2023-03-02 01:28 UTC, dhavalveera commented on src/technologies/a.json
> +      "ApexCharts": ""
the reason for asking is above you mentioned it delete, and here you're saying `I THINK IT WILL BE ENOUGH` so I am completely confused whether to delete it or not

2023-03-04 17:27 UTC, nurbek91 commented on src/technologies/a.json
> +      "ApexCharts": ""
> Do I've to delete the `dom` & `Apex` in JS or what?

yes delete dom and Apex, leave only ApexCharts

2023-03-05 20:07 UTC, nurbek91 approved these changes

2023-03-14 23:57 UTC, merged