Quilljs Rich Text Editor Trace Improved
wappalyzer/wappalyzer pull request #7565
Opened 2023-03-25 08:05 UTC by dhavalveera

**Examples of `link[href]`**:

https://my.iccsafe.org/login
https://games.steelseries.com/home

**Example of `div` class**:

https://zenoamaro.github.io/react-quill/

2023-04-03 15:42 UTC, nurbek91 requested changes
Hey mate , thanks!!

2023-04-03 15:42 UTC, nurbek91 commented on src/technologies/q.json
> +    "dom": "link[href*='cdn\\.quilljs.com/'], div.quill, div.ql-editor",
lets replace to this one
```
"dom": {
      "link[href*='cdn.quilljs.com/']": {
        "attributes": {
          "href": "cdn\\.quilljs\\.com/([\\d\\.]+)/\\;version:\\1"
        }
      }
    },
```

2023-04-04 01:26 UTC, dhavalveera commented on src/technologies/q.json
> +    "dom": "link[href*='cdn\\.quilljs.com/'], div.quill, div.ql-editor",
what about `div.quill` & `div.ql-editor` => this trace is required where CDN isn't being used

2023-04-05 18:47 UTC, nurbek91 approved these changes

2023-04-10 01:34 UTC, AliasIO commented on src/technologies/q.json
> +        "attributes": {
This block can be changed to `"exists": ""`.

2023-04-10 01:34 UTC, AliasIO commented on src/technologies/q.json
> +        "attributes": {
This block can be changed to `"exists": ""`.

2023-04-10 01:37 UTC, dhavalveera commented on src/technologies/q.json
> +        "attributes": {
replace the `attributes` to `exists`?

2023-04-10 01:37 UTC, dhavalveera commented on src/technologies/q.json
> +        "attributes": {
replace the `attributes` to `exists`?

2023-04-10 01:41 UTC, nurbek91 commented on src/technologies/q.json
> +        "attributes": {
```
"div[class*='ql-editor']": {
        "attributes": { 
             "class": "quill"
        }
      },
"div[class*='quill']": {
        "attributes": { 
             "class": "quill"
        }
      },
```
something similar
```
"div[class*='quill'], div[class*='ql-editor'] ": {
"exists": ""
}
```

2023-04-10 01:52 UTC, dhavalveera commented on src/technologies/q.json
> +        "attributes": {
@AliasIO, @nurbek91  - please review this updated PR, is this correct what you mentioned above

2023-04-10 02:20 UTC, nurbek91 commented on src/technologies/q.json
> +        "attributes": {
@dhavalveera  Does the code work locally on the examples?

2023-04-10 02:25 UTC, dhavalveera commented on src/technologies/q.json
> +        "attributes": {
yes, it's working....

2023-04-10 02:27 UTC, nurbek91 approved these changes

2023-04-10 23:54 UTC, merged