Update technology Zyro to Hostinger Website Builder
wappalyzer/wappalyzer pull request #7570
Opened 2023-03-29 08:53 UTC by VytenisSidabras

Changes in technology name, icon, and detection meta tag.

**Website:** 
https://www.hostinger.com/website-builder

**Examples:**
https://www.klausuciualus.lt/
https://acottonphoto.com/
https://www.brahmleen.com/

2023-04-03 15:59 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!

2023-04-03 15:59 UTC, nurbek91 commented on src/technologies/h.json
> +    "description": "Hostinger website builder is easy to use website builder that allows you to create a website in minutes.",
something like this
"description": "Hostinger Website Builder is a web-based platform that allows users to create and design websites without needing to write code or have extensive technical knowledge."

2023-04-04 07:28 UTC, VytenisSidabras commented on src/technologies/h.json
> +    "description": "Hostinger website builder is easy to use website builder that allows you to create a website in minutes.",
Thanks! Updated.

2023-04-04 17:17 UTC, nurbek91 approved these changes

2023-04-10 01:22 UTC, merged