Update Ahoy
wappalyzer/wappalyzer pull request #7621
Opened 2023-04-14 13:19 UTC by osbre

2023-04-15 01:37 UTC, dhavalveera requested changes

2023-04-15 01:37 UTC, dhavalveera commented on src/technologies/a.json
> +    "description": "Ahoy is a Ruby gem that provides simple and powerful analytics for Ruby on Rails applications."
`,` is missing in the end the description line.

```json
"description": "Ahoy is a Ruby gem that provides simple and powerful analytics for Ruby on Rails applications.",
```

2023-04-15 19:48 UTC, nurbek91 reviewed
Hey mate, thanks. Left a comment. It seems nothing critical just a different point of view

2023-04-15 19:48 UTC, nurbek91 commented on src/technologies/a.json
> +    "description": "Ahoy is a Ruby gem that provides simple and powerful analytics for Ruby on Rails applications.",
Maybe something like this,
Ahoy  is a real-time analytics software tool that helps website owners and developers track user behavior and gain insights into how their websites are performing.

2023-04-15 19:48 UTC, nurbek91 commented on src/technologies/a.json
> +    "implies": "Ruby on Rails",
Ahoy Analytics is a web analytics software tool that is designed to work with a variety of different web technologies and programming languages. While Ahoy was originally developed as a Ruby on Rails plugin, it has since been adapted to work with other web frameworks and programming languages such as JavaScript, Python, and PHP.

So, while Ahoy Analytics has roots in the Ruby programming language, it is not limited to use with Ruby-based web applications. It can be used with any web application that can run JavaScript, and it provides a flexible and customizable solution for tracking and analyzing user behavior on the web.

2023-04-15 22:56 UTC, osbre commented on src/technologies/a.json
> +    "implies": "Ruby on Rails",
I think in this case, ChatGPT is lying. Ahoy is a package for Ruby on Rails, and it has not been designed to work with a variety of different web frameworks and programming languages.

Try to ask it again referring to this package as `ankane/ahoy` instead of `ahoy`, I think you would get different results.

2023-04-15 23:06 UTC, osbre commented on src/technologies/a.json
> +    "description": "Ahoy is a Ruby gem that provides simple and powerful analytics for Ruby on Rails applications.",
I'm not sure if this description reflects what Ahoy is best, to give a few points:

It is not a software tool, but a Ruby on Rails package, and packages in the Ruby ecosystem are called "Gems". It is focused on developers, not website owners as it doesn't provide any visual user interface (only JSON endpoints)

2023-04-24 10:35 UTC, nurbek91 commented on src/technologies/a.json
> +    "implies": "Ruby on Rails",
@osbre ok thanks mate

2023-05-30 19:52 UTC, merged