aHrefs SEO Traffic Monitoring Widget Trace Added
wappalyzer/wappalyzer pull request #7659
Opened 2023-05-06 10:35 UTC by dhavalveera

### New Technology Request

**`Examples:`**

https://www.efireplacestore.com/
https://www.additudemag.com/
https://descuentos.abc.es/
https://podcasters.spotify.com/resources/learn
https://eldiariony.com/

2023-05-07 03:33 UTC, dhavalveera commented
@AliasIO @nurbek91  - can you tell/guide me that it's possible to identify any technology using DNS Records (txt) for Web Extension? if it's possible how to identify the DNS (txt) Records?

2023-05-07 16:21 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!

2023-05-07 16:21 UTC, nurbek91 commented on src/technologies/a.json
> +    "description": "Ahrefs is an All-in-one SEO Toolsets To Grow Your Website Search Traffic & Ahrefs Webmaster Tool to Monitor your SEO Health, know your backlinks, see Keywords that gets Traffic",
Ahrefs is an online toolset utilised for search engine optimisation (SEO) and competitor analysis, which permits users to analyse their website's performance, track keyword rankings, identify backlink opportunities, and research competitors' websites, among other features.

2023-05-07 16:21 UTC, nurbek91 commented on src/technologies/a.json
> +      5,
lets remove widget category 5 
and replace with 54 SEO

2023-05-07 16:21 UTC, nurbek91 commented on src/technologies/a.json
> +  "aHrefs": {
aHrefs - > Ahrefs

2023-05-08 22:49 UTC, nurbek91 approved these changes

2023-05-30 19:45 UTC, merged