Add Front-Commerce detection
wappalyzer/wappalyzer pull request #7679
Opened 2023-05-25 09:57 UTC by paul-vd

### Website
- https://front-commerce.com
- https://developers.front-commerce.com/

### Examples
- https://magento2.front-commerce.app/
- https://magento1.front-commerce.app/
- https://magento2-b2b.front-commerce.app/

2023-05-30 10:57 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!

2023-05-30 10:57 UTC, nurbek91 commented on src/technologies/f.json
> +    "icon": "front-commerce.svg",
![Front-Commerce](https://github.com/wappalyzer/wappalyzer/assets/3456008/8f803205-329d-4119-92cf-4014d5ec5301)
32x32

2023-05-30 10:57 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
Leave only category 6
```
"cats": [
      6,
    ],
```

2023-05-30 10:57 UTC, nurbek91 commented on src/technologies/f.json
> +    "description": "An API-first, headless e-commerce framework with PWA capabilities and a fast, customizable frontend.",
Front-Commerce is a React-based ecommerce framework that provides a development environment and tools for building online stores, offering seamless integration with backend systems through GraphQL and supporting popular ecommerce platforms like Magento and Pimcore.

2023-05-30 10:57 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
```
 "implies": [
      "React",
      "GraphQL",
      "Webpack",
      "Node.js"
    ],
```

2023-06-14 10:38 UTC, paul-vd commented on src/technologies/f.json
> +    ],
Hmm, would it not also deserve **12**, and **18**? and also maybe **22**?

In itself it is not e-commerce at all, but instead proves the tools as framework for other developers to build an e-commerce site using front-commerce, simular to remix / nextjs / blitzjs, it handles everything related to bundling, tools, server, client, caching, etc...  so only category 6 seems incorrect?

Also it's not limited to e-commerce, it has full cms integrations as well, for example wordpress, prismic, contentful.

2023-06-14 10:55 UTC, paul-vd commented on src/technologies/f.json
> +    "description": "An API-first, headless e-commerce framework with PWA capabilities and a fast, customizable frontend.",
I'm checking with the team for the best description, thanks for the proposal, it's indeed better 😄 ✍🏻  I will amend my PR once I got feedback from them.

2023-06-14 12:44 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
Hey @paul-vd
My mistake should probably leave the 108 category Ecommerce frontends

2023-06-14 12:46 UTC, nurbek91 commented on src/technologies/f.json
> +    "description": "An API-first, headless e-commerce framework with PWA capabilities and a fast, customizable frontend.",
Yes, any description will do. 
Starting like->  Front-Commerce is a ..... 
and need use UK spelling

2023-06-14 12:52 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
https://www.wappalyzer.com/technologies/ecommerce-frontends/ if these are direct competitors, Front-Commerce  technology should also be on this list

2023-06-14 14:12 UTC, paul-vd commented on src/technologies/f.json
> +    "description": "An API-first, headless e-commerce framework with PWA capabilities and a fast, customizable frontend.",
It has been updated 😉

2023-06-14 18:18 UTC, nurbek91 approved these changes

2023-06-14 18:19 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
I did not understand the question. But everything looks right now

2023-06-15 06:22 UTC, paul-vd commented on src/technologies/f.json
> +    ],
The tracking of different competitors on https://www.wappalyzer.com/technologies/ecommerce-frontends, is it based on the defined category of each service?  for example **108**

2023-06-15 21:53 UTC, nurbek91 commented on src/technologies/f.json
> +    ],
Ah yes mate!

2023-07-04 22:32 UTC, merged

2023-07-04 22:32 UTC, AliasIO commented
Thanks!

2023-07-06 15:39 UTC, paul-vd commented
@AliasIO @nurbek91 we recently made a change in our packaging to improve loading performance, so the latest version of our service no longer has the link tag, I added a new PR to fix this: https://github.com/wappalyzer/wappalyzer/pull/7791