Add Kudobuzz detection
wappalyzer/wappalyzer pull request #7682
Opened 2023-05-25 18:33 UTC by khempenius

website:
https://kudobuzz.com/
https://github.com/kudobuzz

examples:
https://www.theringerhoops.com/
https://www.ericraviliousprints.com/
https://www.sayitwithflowers.uk.com/
https://www.thepureindianstore.com/
https://www.snogear.com/

2023-05-30 11:03 UTC, nurbek91 commented on src/technologies/k.json
> +    "icon": "Kudobuzz.png",
![Kudobuzz](https://github.com/wappalyzer/wappalyzer/assets/3456008/9463b1d4-d097-4dd5-a93d-498e28e8b1ec)
32x32 svg

2023-05-30 11:05 UTC, nurbek91 commented on src/technologies/k.json
> +    },
we can remove this trace due redundancy

2023-05-30 11:06 UTC, nurbek91 commented on src/technologies/k.json
> +    },
for complete certainty
```
"js": {
      "Kudos.apiServer": "api\\.kudobuzz\\.com"
    },
```

2023-05-30 11:08 UTC, nurbek91 requested changes

2023-05-30 11:08 UTC, nurbek91 commented on src/technologies/k.json
> +      5
90 reviews category

2023-06-02 10:30 UTC, nurbek91 approved these changes

2023-06-12 23:25 UTC, merged

2023-06-12 23:26 UTC, AliasIO commented
Thanks!