Algolia Detection Improved & Version Detection added
wappalyzer/wappalyzer pull request #7683
Opened 2023-05-27 10:57 UTC by dhavalveera

### Technology Improvement

**`Examples:`**

**for version Detection using:  __algolia.algoliasearch.version**:

- https://stripe.com/docs/api
- https://api.jquery.com/
- https://classic.yarnpkg.com/lang/en/

**using a[href]:**

- https://fontawesome.com/search

2023-05-30 11:18 UTC, nurbek91 requested changes
Hey mate, thanks for PR!

2023-05-30 11:18 UTC, nurbek91 commented on src/technologies/a.json
> +    "dom": "a[href*='algolia\\.com']",
Technology is defined without this trace
![image](https://github.com/wappalyzer/wappalyzer/assets/3456008/eb501e7e-25da-472e-9c6f-0be90c56029a)

2023-05-31 01:30 UTC, dhavalveera commented on src/technologies/a.json
> +    "dom": "a[href*='algolia\\.com']",
@nurbek91 - when I am checking the FontAwesome Website, it's not able to detect the Algolia, it's able to get detected with `"dom"` trace only

2023-06-05 09:22 UTC, nurbek91 commented on src/technologies/a.json
> +    "dom": "a[href*='algolia\\.com']",
@dhavalveera Can you open this example several times and wait until the technology is displayed

2023-06-07 00:40 UTC, nurbek91 approved these changes

2023-06-12 23:25 UTC, merged