Add Brimble / PaaS
wappalyzer/wappalyzer pull request #7773
Opened 2023-06-25 14:31 UTC by klefcodes

### website:
https://brimble.io

### examples:
https://www.sidekyk.app
https://usecrim.brimble.app
https://getfastrack.app
https://heinz.brimble.app

2023-06-27 04:26 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!
Cosmetic changes required

2023-06-27 04:26 UTC, nurbek91 commented on src/technologies/b.json
> +    "icon": "brimble.svg",
![Brimble](https://github.com/wappalyzer/wappalyzer/assets/3456008/8e9bd1b6-638c-4bd3-b8bc-e6611c9000fb)
32x32

2023-06-27 04:26 UTC, nurbek91 commented on src/technologies/b.json
> +  "brimble": {
Brimble

2023-06-27 04:26 UTC, nurbek91 commented on src/technologies/b.json
> +    "description": "Brimble is a cloud platform for deploying frontend web applications",
"description": "Brimble is a cloud platform for deploying frontend web applications.",

2023-07-03 16:36 UTC, nurbek91 approved these changes

2023-07-04 22:38 UTC, merged

2023-07-04 22:38 UTC, AliasIO commented
Thanks!