Colbass Trace Detection added
wappalyzer/wappalyzer pull request #7774
Opened 2023-06-26 01:47 UTC by dhavalveera

#7771

2023-06-27 04:54 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!

2023-06-27 04:54 UTC, nurbek91 commented on src/technologies/c.json
> +    "dom": "audio#colbass-tts-audio",
Please check whether it is possible to determine the technology using this trace. The less resource intensive option should be
```
"js": {
      "colbassRunning": ""
    },
```

2023-06-27 04:54 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "colbass.png",
32x32
![Colbass](https://github.com/wappalyzer/wappalyzer/assets/3456008/30185d26-1e7a-4801-8476-fb4a93e12a5c)
Icon with transparent background

2023-06-27 04:54 UTC, nurbek91 commented on src/technologies/c.json
> +    ],
```
"pricing": [
      "low",
      "onetime",
      "recurring"
    ],
```

2023-06-27 04:54 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "colbass.png",
https://github.com/wappalyzer/wappalyzer/pull/7667#issuecomment-1557672416
Here, too, an icon with a transparent background is needed, if not, could you write that the request cannot be completed

2023-06-28 01:16 UTC, dhavalveera commented on src/technologies/c.json
> +    "icon": "colbass.png",
I didn't get you for the 2nd message where you've mentioned another PR

2023-07-03 16:36 UTC, nurbek91 commented on src/technologies/c.json
> +    "icon": "colbass.png",
ok never-mind

2023-07-03 16:37 UTC, nurbek91 approved these changes

2023-07-04 22:38 UTC, merged