Add Wayforpay detection
wappalyzer/wappalyzer pull request #7779
Opened 2023-06-29 12:14 UTC by osbre

2023-07-03 17:04 UTC, nurbek91 requested changes
Hey mate, thanks!!
All edits as an alternative that is responsible for optimisation

2023-07-03 17:04 UTC, nurbek91 commented on src/technologies/w.json
> +    "dom": "form[action*='secure.wayforpay.com']",
instead **dom** and **scriptSrc** maybe only js will be enough? 
```
"js": {
      "WayforpayInitParams": ""
    },
```

2023-07-09 22:42 UTC, osbre commented on src/technologies/w.json
> +    "dom": "form[action*='secure.wayforpay.com']",
No, we cannot rely only on JS because there are cases when HTML form is used (I believe such usage is also very active, possibly even more popular than the JS library)

2023-07-10 08:15 UTC, nurbek91 commented on src/technologies/w.json
> +    "dom": "form[action*='secure.wayforpay.com']",
Fine. Do you have examples other than demo. I could not find examples where all these traces are used.

2023-07-26 23:49 UTC, merged