Add Tiiny Host detection
wappalyzer/wappalyzer pull request #7781
Opened 2023-06-29 12:45 UTC by osbre

Examples: https://www.google.com/search?q=site%3Atiiny.site

2023-07-04 12:44 UTC, nurbek91 reviewed
Hey mate, thanks!!!

2023-07-04 12:44 UTC, nurbek91 commented on src/technologies/t.json
> +    "url": "\\.(?:tiiny\\.site|tiiny\\.co)",
Can we use sciptSrc instead of url? to be able to define web sites with custom domains? Although I'm not sure what the link will be to javascript files on such sites
https://tiiny.host/ad-script.js
https://analytics.tiiny.site/js/plausible.js

2023-07-09 22:35 UTC, osbre commented on src/technologies/t.json
> +    "url": "\\.(?:tiiny\\.site|tiiny\\.co)",
Thanks, updated.

2023-07-10 08:20 UTC, nurbek91 requested changes

2023-07-10 08:20 UTC, nurbek91 commented on src/technologies/t.json
> +    "scriptSrc": "https://tiiny.host/ad-script.js",
`"scriptSrc": "(?://|\\.)tiiny\\.(?:host|site)/",
`

2023-07-26 23:50 UTC, merged