Add See5 WebsiteBuilder
wappalyzer/wappalyzer pull request #7785
Opened 2023-07-01 12:58 UTC by hosina

Add See5 WebsiteBuilder

2023-07-04 12:54 UTC, nurbek91 requested changes
Hey mate, thanks!!!
Could you please provide links to examples.

2023-07-04 12:54 UTC, nurbek91 commented on src/technologies/s.json
> +     "website": "https://see5.net"
page does not open

2023-07-04 12:54 UTC, nurbek91 commented on src/technologies/s.json
> +    ],
It is not recommended to use it due to resource consumption.

2023-07-04 12:54 UTC, nurbek91 commented on src/technologies/s.json
> +    ],
it is desirable to indicate 1 category maximum 2

2023-07-07 21:36 UTC, hosina commented
website:see5.net 
example:sitetesttarahi006.see5.net

2023-07-07 21:40 UTC, nurbek91 commented
> see5.net

2023-07-07 21:41 UTC, nurbek91 commented
> website:see5.net example:sitetesttarahi006.see5.net
But this site is built using Wordpress and wpBakery
![image](https://github.com/wappalyzer/wappalyzer/assets/3456008/a322218d-f14e-49ff-adc4-a6f2a8260080)

2023-07-07 21:45 UTC, hosina commented
see5 website builder is saas service for build website with wordpress with pagebuilder 

example site: https://sitetesttarahi006.see5.net/

2023-07-26 23:53 UTC, closed without merging