Add ID5 detection
wappalyzer/wappalyzer pull request #7792
Opened 2023-07-07 10:26 UTC by max-ostapenko

Website: https://id5.io

One of the prominent cookie-alternative audience solutions: https://blog.admixer.com/cookie-alternatives/

Examples:
1. https://adamtheautomator.com/
2. https://actu.fr/

2023-07-07 21:56 UTC, nurbek91 requested changes
Hey mate, thanks for PR!!!
more examples
http://cphpost.dk/
https://jubii.dk/

2023-07-07 21:56 UTC, nurbek91 commented on src/technologies/i.json
> +    "icon": "ID5.png",
![ID5](https://github.com/wappalyzer/wappalyzer/assets/3456008/a094cdc2-0cbb-47aa-b5b4-0f1709cea12e)
svg

2023-07-07 21:56 UTC, nurbek91 commented on src/technologies/i.json
> +    "description": "ID5 is the leading identity provider powering addressable advertising for brands, publishers, and their technology partners.",
ID5 is a company that offers an identity solution for digital advertising, providing a Universal ID that enables privacy-compliant user recognition and tracking across websites without relying on personal information or third-party cookies.

2023-07-07 21:56 UTC, nurbek91 commented on src/technologies/i.json
> +    ],
maybe use one cat 67 - > Cookie compliance

2023-07-07 21:56 UTC, nurbek91 commented on src/technologies/i.json
> +    ],
`"scriptSrc": "^https://(?:cdn\\.)?id5-sync\\.com/",`

looks redundant
`"id5-api\\.js"`

2023-07-07 21:56 UTC, nurbek91 commented on src/technologies/i.json
> +    }
```
"js": {
      "ID5._version": "^(.+)$\\;version:\\1",
      "__id5_instances": ""
    },
```

2023-07-08 10:18 UTC, max-ostapenko commented on src/technologies/i.json
> +    "icon": "ID5.png",
@nurbek91 @AliasIO is SVG a preferred format?

2023-07-08 10:31 UTC, max-ostapenko commented on src/technologies/i.json
> +    ],
It's not compliance management, and functions as a cookie-sync alternative.
33Across is the most similar existing tech.

If you'd like to keep only one category then let's have 36.

2023-07-09 11:00 UTC, nurbek91 approved these changes

2023-07-09 11:01 UTC, nurbek91 commented on src/technologies/i.json
> +    "icon": "ID5.png",
Hey @max-ostapenko , yes SVG preferred format

2023-07-26 23:54 UTC, merged

2023-07-26 23:54 UTC, AliasIO commented
Thanks!