Add Progress MOVEit / miscellaneous
wappalyzer/wappalyzer pull request #7802
Opened 2023-07-11 14:03 UTC by francisco-sec

Added support for Progress MOVEit, using different methods:
- meta headers
- style tags
- scripts content
- MOVEit version via api headers 

**Website:**
[https://www.progress.com/moveit](https://www.progress.com/moveit)

**Examples:**
[https://mft.us.sumitomo-pharma.com](https://mft.us.sumitomo-pharma.com)
[https://moveitpay.fisglobal.com](https://moveitpay.fisglobal.com)

2023-07-11 19:29 UTC, ceopeo requested changes
Hey mate, thanks for PR!!

2023-07-11 19:29 UTC, ceopeo commented on src/technologies/m.json
> +    "icon": "MOVEit.png",
![Progress](https://github.com/wappalyzer/wappalyzer/assets/3456008/b3e70cd3-31da-48be-b4db-1964bdad4514)
Preferred svg format. You can leave the name Progress.svg

2023-07-11 19:29 UTC, ceopeo commented on src/technologies/m.json
> +  "MOVEit": {
`"Progress MOVEit": {`

Can you name the technology that way. Later I will try to combine the products of this organisation

2023-07-11 19:29 UTC, ceopeo commented on src/technologies/m.json
> +    "description": "MOVEit is a Secure File Transfer and Automation Software for the Enterprise",
`"description": "Progress MOVEit is a managed file transfer solution that enables secure and compliant transfer of sensitive files while providing automation, central management, and auditing capabilities.",`

2023-07-11 19:29 UTC, ceopeo commented on src/technologies/m.json
> +    ],
Looks redundant and resource intensive can be removed

2023-07-11 19:29 UTC, ceopeo commented on src/technologies/m.json
> +    },
I think enough
```
 "meta": {
      "smartbanner:title": "MOVEit\\sMobile",
      "smartbanner:button-url-google": "com\\.progress\\.moveit\\.transfer\\.dev\\.appid"
    },
```

2023-07-12 09:33 UTC, francisco-sec commented on src/technologies/m.json
> +    "icon": "MOVEit.png",
All good, included that svg. What are your thoughts on using this one instead?
![Progress](https://github.com/wappalyzer/wappalyzer/assets/4529567/8ca5e205-4b94-487b-baac-9b1df0463b8c)

2023-07-12 09:35 UTC, francisco-sec commented on src/technologies/m.json
> +  "MOVEit": {
Sure, it makes sense. Renamed the technology and moved it to the p.json file.

2023-07-12 10:23 UTC, francisco-sec commented on src/technologies/m.json
> +    "description": "MOVEit is a Secure File Transfer and Automation Software for the Enterprise",
updated

2023-07-12 10:33 UTC, francisco-sec commented on src/technologies/m.json
> +    },
The filters you are suggesting might not be enough to identify Progress MOVEit as there are two distinct ways to define smartbanner properties:

1. Using inline js 
```html
<script type="application/javascript" nonce="Gz4Z9TZxgrLVDM4hc4NiM9p1">
	$(function() {
		$.smartbanner({
		  title: 'MOVEit Mobile',
		  author: 'Progress Software Corporation',
		  price: 'Free',
		  inGooglePlay: 'On the Google Play',
		  icon: 'images/MoveitMobileIcon.png',
		  button: 'View',
		  scale: 1,
		});
	});
</script>
```

2. Using meta headers
```html
<meta name="apple-itunes-app" content="app-id=1500056420">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="smartbanner:title" content="MOVEit Mobile">
<meta name="smartbanner:author" content="Progress Software Corporation">
<meta name="smartbanner:price" content="Free">
<meta name="smartbanner:price-suffix-google" content=" - On the Google Play">
<meta name="smartbanner:icon-google" content="../images/MoveitMobileIcon.png">
<meta name="smartbanner:button" content="View">
<meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=com.progress.moveit.transfer.dev.appid">
<meta name="smartbanner:enabled-platforms" content="android">
<meta name="smartbanner:close-label" content="Close">
<meta name="smartbanner:api" content="true">
```

We'll need to find a better tradeoff to identify both cases.

2023-07-12 10:37 UTC, francisco-sec commented on src/technologies/m.json
> +    ],
I believe we can drop the style check, as companies using the product might choose not to use any moveit css anyway. Regarding the scripts I'm not sure they can all be dropped because relying on meta tags doesn't seem enough (please check comments below about meta headers)

2023-07-12 11:13 UTC, ceopeo commented on src/technologies/m.json
> +    },
It is undesirable to include all traces. Usually one common for all is enough.
I checked the examples you provided and advised  to leave a common thread in these examples.
If additional tracking tags need to be added, examples will need to be provided. By examples, we can tell if it is worth adding additional cases

2023-07-12 11:57 UTC, francisco-sec commented on src/technologies/m.json
> +    },
I have done some sampling statistics in order to optimize our filters as you suggested.
Please find the results below:
```
1. @import "templates/stylesheet_MOVEit_*" - 80%

2. <meta name="apple-itunes-app" content="app-id=1500056420"> - 100%

3. <meta name="google-play-app" content="app-id=com.progress.moveit.transfer.dev.appid"> - 75%

4. $.smartbanner({ title: 'MOVEit Mobile',... - 75%

5. <meta name="smartbanner:title" content="MOVEit Mobile"> - 30%

6. MOVEitPopUp - 100%
```
Giving the data collected, I propose we only use the following instead:

```
 "meta": {
      "apple-itunes-app": "app-id=1500056420",
      "google-play-app": "app-id=com\\.progress\\.moveit\\.transfer\\.dev\\.appid",
    },
```
Despite points 1, 4 and 6 having a high frequency, I believe we could drop them as they are resource intensive.

Let me know your thoughts on this.

2023-07-12 16:23 UTC, ceopeo commented on src/technologies/m.json
> +    },
Hey mate again, Okay, let's leave everything in the meta and delete the rest **scripts, dom**

2023-07-12 18:48 UTC, francisco-sec commented on src/technologies/m.json
> +    },
Hello again, thanks for your feedback!
I have already changed the code as we discussed previously.
Regarding its accuracy, took the initiative to run **src/drivers/npm/cli.js** against 50 Progress MOVEit hosts, giving only positive results, as expected. So I believe its good to go ;)

2023-07-12 19:30 UTC, ceopeo approved these changes

2023-07-12 19:31 UTC, ceopeo commented on src/technologies/m.json
> +    },
that's good to hear

2023-07-26 23:58 UTC, merged