Add Progress WS_FTP / miscellaneous
wappalyzer/wappalyzer pull request #7854
Opened 2023-07-19 15:12 UTC by francisco-sec

Added support for Progress WS_FTP, using dom fingerprint.

Website:
https://www.progress.com/ws_ftp

Examples:
https://ftp.atitesting.com/ (Recent Web Transfer Client)
https://sftp.nlacrc.org/thinclient/ (Older Web Transfer Client)

2023-07-20 16:37 UTC, ceopeo requested changes
Hey mate, thanks!!!

2023-07-20 16:37 UTC, ceopeo commented on src/technologies/p.json
> +  "Progress WS_FTP": {
Can we add such a line? This would help optimise the search.
"requires": "Microsoft ASP.NET",

2023-07-20 16:37 UTC, ceopeo commented on src/technologies/p.json
> +    "description": "The Progress WS_FTP software provides both an effective, highly manageable FTP server and the ability to provide each user a secure FTP client, assuring both reliability and secur
Progress WS_FTP is a file transfer client software developed by Progress Software Corporation, supporting FTP, FTPS, SFTP, and HTTPS protocols with features like drag-and-drop support, file synchronization, and encrypted data transmission.

2023-07-20 16:37 UTC, ceopeo commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
Looks like a very broad search. Are there other indirect signs that will add confidence to us?
`"requires": .....`

2023-07-21 10:56 UTC, francisco-sec commented on src/technologies/p.json
> +  "Progress WS_FTP": {
Sure, that would be a great improvement. Just checked in several instances, and wappalyzer was able to recognize ASP.NET in all of them

2023-07-21 10:57 UTC, francisco-sec commented on src/technologies/p.json
> +    "description": "The Progress WS_FTP software provides both an effective, highly manageable FTP server and the ability to provide each user a secure FTP client, assuring both reliability and secur
done

2023-07-21 13:50 UTC, francisco-sec commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
Indeed, this one was the best I could found after analyzing dozens of different instances.
WS_FTP recent instances are using angular and bootstrap for the frontend...
However, if we add those requires, we might start having false negatives on old instances

It took me a long time to find this dom pattern, but please find below some others (only valid for recent instances):
Title: "Web Transfer Client" (Could get a lot of false positives)
Using url: /ThinClient/WTM/public/index.html
Having 'percent=\"{{progress}}\"' on html

Let me know your thoughts, and if only detecting recent instances would be a better tradeoff

2023-07-23 13:56 UTC, ceopeo commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
` "scriptSrc": "/ThinClient/(?:WTM|WebResource)(?:\\.axd|/public)",`

2023-07-23 14:01 UTC, ceopeo commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
Can we replace dom with scriptSrc. After adding "requires": "Microsoft ASP.NET", the code is much better optimized and won't run every time.

If you are not sure  **dom** gives 100 confidence you can change like this
"dom": "form[name='formLogin'][action='login.aspx' i][id='formLogin']\\;confidence:40",
"scriptSrc": "/ThinClient/(?:WTM|WebResource)(?:\\.axd|/public)\\;confidence:60"",

2023-07-23 14:54 UTC, francisco-sec commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
It was a great idea using that scriptSrc. Unfortunately, we can not rely only on scriptSrc as it will lead to a false negative rate of 30%.
Combining the dom and the ScriptSrc we can reach a false negative rate of 10%, also, both solutions won't produce false positives.
Taking this numbers into account, do you agree in keeping dom and scriptSrc?

2023-07-23 22:01 UTC, ceopeo commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
Below 50 percent, the extension does not show in the results, but the npm driver will show at least 0, 30, 60
maybe something like this 
```
"dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']\\;confidence:30",
"scriptSrc": "/ThinClient/(?:WTM|WebResource)(?:\\.axd|/public)\\;confidence:30"",
```

2023-07-24 09:47 UTC, francisco-sec commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
Dom filter like that is able to detect almost all cases, so does it make sense to give it a confidence of 30?

2023-07-26 22:07 UTC, ceopeo commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
it's just that there are no keywords similar to the names of technologies, so that there were no false positive results, I wanted to include additional parameters

2023-07-27 00:11 UTC, merged

2023-07-27 06:56 UTC, francisco-sec commented on src/technologies/p.json
> +    "dom": "spinner[class='spinner-wrap'][percent=''], form[name='formLogin'][action='login.aspx' i][id='formLogin']",
I see, it makes sense to me now. Thanks for all your help!