added basilcss to wappalyzer
wappalyzer/wappalyzer pull request #7894
Opened 2023-08-03 13:31 UTC by daniel-bergmann

Added basilcss to wappalyzer

2023-08-03 19:06 UTC, ceopeo requested changes
Hey mate, thanks for PR!!

- need examples
- and traces how can we define technology

2023-08-03 19:06 UTC, ceopeo commented on src/technologies/b.json
> +    "icon": "basilcss.svg",
need 32x32

2023-08-03 19:06 UTC, ceopeo commented on src/technologies/b.json
> +    "description": "The CSS framework made with the goal of bridging the gap between developers who like using UI frameworks and those who prefer styling apps without them.",
Basil.css is a responsive and customisable UI framework.

2023-08-03 19:06 UTC, ceopeo commented on src/technologies/b.json
> +      18
66

2023-08-03 19:06 UTC, ceopeo commented on src/technologies/b.json
> +    "npm": ["basilcss"]
What is this line for?

2023-08-04 07:35 UTC, daniel-bergmann commented on src/technologies/b.json
> +      18
fixed.

2023-08-04 07:35 UTC, daniel-bergmann commented on src/technologies/b.json
> +    "description": "The CSS framework made with the goal of bridging the gap between developers who like using UI frameworks and those who prefer styling apps without them.",
fixed.

2023-08-04 07:35 UTC, daniel-bergmann commented on src/technologies/b.json
> +    "icon": "basilcss.svg",
added.

2023-08-04 07:36 UTC, daniel-bergmann commented on src/technologies/b.json
> +    "npm": ["basilcss"]
removed, propably just a brainfart.

2023-08-04 07:38 UTC, daniel-bergmann commented
Thanks for the feedback @ceopeo, how does it look now?

2023-08-07 07:02 UTC, ceopeo reviewed
This is an example of how Tailwind CSS is detected
`"scriptSrc": "\\.tailwindcss(?:tailwind-config-cdn)?\\.(?:com|js)",`

2023-08-07 10:42 UTC, daniel-bergmann commented
Hi there @ceopeo, thanks for your feedback!

I've added the tracers and tried to test it locally by visiting https://basilcss.com/ and https://daniel-bergmann.github.io/pomo-todo/

Do you have any other idea how to improve or should we plug it in?

2023-08-08 01:51 UTC, AliasIO commented
Sorry, the [diff](https://github.com/wappalyzer/wappalyzer/pull/7894/files) is a bit of a mess. Would you mind rebasing or re-applying your changes?

2023-08-08 08:23 UTC, daniel-bergmann commented
allrighty then, ill make a new pull request

2023-08-08 08:23 UTC, closed without merging